// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ResourceArgs {
    pub data: crate::types::DataArgs,
}

impl ResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.data;
            inputs.push(("data".to_string(), v.into_output()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Resource {
    resource: pulumi::Resource,
}

impl Resource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "primitive-ref:index:Resource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "11.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Resource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn data(&self) -> pulumi::Output<crate::types::Data> {
        self.resource.output("data").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:primitive-ref".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "11.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct DataArgs {
        pub bool_array: pulumi::Output<std::vec::Vec<bool>>,
        pub boolean: pulumi::Output<bool>,
        pub float: pulumi::Output<f64>,
        pub integer: pulumi::Output<i32>,
        pub string: pulumi::Output<std::string::String>,
        pub string_map: pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>,
    }

    impl DataArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.bool_array;
                inputs.push(("boolArray".to_string(), v.cast()));
            }
            {
                let v = self.boolean;
                inputs.push(("boolean".to_string(), v.cast()));
            }
            {
                let v = self.float;
                inputs.push(("float".to_string(), v.cast()));
            }
            {
                let v = self.integer;
                inputs.push(("integer".to_string(), v.cast()));
            }
            {
                let v = self.string;
                inputs.push(("string".to_string(), v.cast()));
            }
            {
                let v = self.string_map;
                inputs.push(("stringMap".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug)]
    pub struct Data {
        pub bool_array: std::vec::Vec<bool>,
        pub boolean: bool,
        pub float: f64,
        pub integer: i32,
        pub string: std::string::String,
        pub string_map: std::collections::BTreeMap<std::string::String, std::string::String>,
    }

    impl pulumi::FromPropertyValue for Data {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Data {
                bool_array: pulumi::convert::from_property_map(&m, "boolArray")?,
                boolean: pulumi::convert::from_property_map(&m, "boolean")?,
                float: pulumi::convert::from_property_map(&m, "float")?,
                integer: pulumi::convert::from_property_map(&m, "integer")?,
                string: pulumi::convert::from_property_map(&m, "string")?,
                string_map: pulumi::convert::from_property_map(&m, "stringMap")?,
            })
        }
    }
}
