// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:any-type-function".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "15.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug, Default)]
pub struct DynListToDynArgs {
    pub inputs: Option<pulumi::Output<std::vec::Vec<pulumi::PropertyValue>>>,
}

impl DynListToDynArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.inputs {
            inputs.push(("inputs".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn dyn_list_to_dyn(ctx: &pulumi::Context, args: DynListToDynArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::DynListToDynResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "15.0.0".to_string();
    }
    ctx.invoke("any-type-function:index:dynListToDyn", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct DynListToDynResult {
        pub result: pulumi::PropertyValue,
    }

    impl pulumi::FromPropertyValue for DynListToDynResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(DynListToDynResult {
                result: pulumi::convert::from_property_map(&m, "result")?,
            })
        }
    }
}
