// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res1 = pulumi_names::ResMap::new(&ctx, "res1", pulumi_names::ResMapArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let res2 = pulumi_names::ResArray::new(&ctx, "res2", pulumi_names::ResArrayArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let res3 = pulumi_names::ResList::new(&ctx, "res3", pulumi_names::ResListArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let res4 = pulumi_names::ResResource::new(&ctx, "res4", pulumi_names::ResResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let res5 = pulumi_names::r#mod::Res::new(&ctx, "res5", pulumi_names::r#mod::ResArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let res6 = pulumi_names::mod_nested::Res::new(&ctx, "res6", pulumi_names::mod_nested::ResArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
