// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        ctx.export("zero", pulumi::pv::number(0.0));
        ctx.export("one", pulumi::pv::number(1.0));
        ctx.export("e", pulumi::pv::number(2.718));
        ctx.export("minInt32", pulumi::pv::number(-2.147483648e+09));
        ctx.export("max", pulumi::pv::number(1.7976931348623157e+308));
        ctx.export("min", pulumi::pv::number(5e-324));
        Ok(())
    });
}
