// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let an_object = ctx.config().require_object("anObject")?;
        let any_object = ctx.config().require_object("anyObject")?;
        let l = pulumi::pv::secret(pulumi::pv::array(vec![pulumi::pv::number(1.0)]));
        let m = pulumi::pv::secret(pulumi::pv::object(vec![("key".to_string(), pulumi::pv::bool(true))]));
        let c = pulumi::pv::secret(an_object.clone());
        let o = pulumi::pv::secret(pulumi::pv::object(vec![("property".to_string(), pulumi::pv::string("value"))]));
        let a = pulumi::pv::secret(any_object.clone());
        ctx.export("l", l.clone().index(0usize));
        ctx.export("m", m.clone().index("key"));
        ctx.export("c", c.clone().index("property"));
        ctx.export("o", o.clone().index("property"));
        ctx.export("a", a.clone().index("property"));
        Ok(())
    });
}
