// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ResourceArgs {
    pub external_enum: pulumi::Output<std::string::String>,
    pub r#in: pulumi::Output<bool>,
}

impl ResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.external_enum;
            inputs.push(("externalEnum".to_string(), v.cast()));
        }
        {
            let v = self.r#in;
            inputs.push(("in".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Resource {
    resource: pulumi::Resource,
}

impl Resource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "docs:index:Resource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "28.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Resource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn data(&self) -> pulumi::Output<crate::types::ResourceData> {
        self.resource.output("data").cast()
    }

    pub fn external_enum(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("externalEnum").cast()
    }

    pub fn r#in(&self) -> pulumi::Output<Option<bool>> {
        self.resource.output("in").cast()
    }

    pub fn out(&self) -> pulumi::Output<bool> {
        self.resource.output("out").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:docs".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "28.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct FunArgs {
    pub r#in: pulumi::Output<bool>,
}

impl FunArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.r#in;
            inputs.push(("in".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn fun(ctx: &pulumi::Context, args: FunArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::FunResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "28.0.0".to_string();
    }
    ctx.invoke("docs:index:fun", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct ResourceData {
        pub state: std::string::String,
    }

    impl pulumi::FromPropertyValue for ResourceData {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(ResourceData {
                state: pulumi::convert::from_property_map(&m, "state")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct FunResult {
        pub out: bool,
    }

    impl pulumi::FromPropertyValue for FunResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(FunResult {
                out: pulumi::convert::from_property_map(&m, "out")?,
            })
        }
    }
}
