// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let string_or_integer_example1 = pulumi_union::Example::new(&ctx, "stringOrIntegerExample1", pulumi_union::ExampleArgs { map_map_union_property: None, string_enum_union_list_property: None, string_or_integer_property: Some(pulumi::ops::to_int(pulumi::pv::number(42.0)).cast()), typed_enum_property: None }, pulumi::ResourceOptions::default());
        let string_or_integer_example2 = pulumi_union::Example::new(&ctx, "stringOrIntegerExample2", pulumi_union::ExampleArgs { map_map_union_property: None, string_enum_union_list_property: None, string_or_integer_property: Some(pulumi::ops::to_int(pulumi::pv::string("forty two")).cast()), typed_enum_property: None }, pulumi::ResourceOptions::default());
        let map_map_union_example = pulumi_union::Example::new(&ctx, "mapMapUnionExample", pulumi_union::ExampleArgs { map_map_union_property: Some(pulumi::pv::object(vec![("key1".to_string(), pulumi::pv::object(vec![("key1a".to_string(), pulumi::ops::to_string(pulumi::pv::string("value1a")))]))]).cast()), string_enum_union_list_property: None, string_or_integer_property: None, typed_enum_property: None }, pulumi::ResourceOptions::default());
        ctx.export("mapMapUnionOutput", map_map_union_example.map_map_union_property().cast::<pulumi::PropertyValue>());
        let string_enum_union_list_example = pulumi_union::Example::new(&ctx, "stringEnumUnionListExample", pulumi_union::ExampleArgs { map_map_union_property: None, string_enum_union_list_property: Some(pulumi::pv::array(vec![pulumi::ops::to_string(pulumi::pv::string("Listen")), pulumi::ops::to_string(pulumi::pv::string("Send")), pulumi::ops::to_string(pulumi::pv::string("NotAnEnumValue"))]).cast()), string_or_integer_property: None, typed_enum_property: None }, pulumi::ResourceOptions::default());
        let safe_enum_example = pulumi_union::Example::new(&ctx, "safeEnumExample", pulumi_union::ExampleArgs { map_map_union_property: None, string_enum_union_list_property: None, string_or_integer_property: None, typed_enum_property: Some(pulumi::ops::to_string(pulumi::pv::string("Block")).cast()) }, pulumi::ResourceOptions::default());
        let enum_output_example = pulumi_union::EnumOutput::new(&ctx, "enumOutputExample", pulumi_union::EnumOutputArgs { name: pulumi::ops::to_string(pulumi::pv::string("example")).cast() }, pulumi::ResourceOptions::default());
        let output_enum_example = pulumi_union::Example::new(&ctx, "outputEnumExample", pulumi_union::ExampleArgs { map_map_union_property: None, string_enum_union_list_property: None, string_or_integer_property: None, typed_enum_property: Some(pulumi::ops::to_string(enum_output_example.r#type().cast::<pulumi::PropertyValue>()).cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
