// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res = pulumi_secret::Resource::new(&ctx, "res", pulumi_secret::ResourceArgs { private: pulumi::ops::to_string(pulumi::pv::string("closed")).cast(), private_array: pulumi::pv::array(vec![pulumi::ops::to_string(pulumi::pv::string("closed"))]).cast(), private_data: pulumi_secret::types::DataArgs { private: pulumi::ops::to_string(pulumi::pv::string("closed")).cast(), public: pulumi::ops::to_string(pulumi::pv::string("open")).cast() }, private_data_array: vec![pulumi_secret::types::DataArgs { private: pulumi::ops::to_string(pulumi::pv::string("closed")).cast(), public: pulumi::ops::to_string(pulumi::pv::string("open")).cast() }], private_data_map: std::collections::BTreeMap::from([("key".to_string(), pulumi_secret::types::DataArgs { private: pulumi::ops::to_string(pulumi::pv::string("closed")).cast(), public: pulumi::ops::to_string(pulumi::pv::string("open")).cast() })]), private_map: pulumi::pv::object(vec![("key".to_string(), pulumi::ops::to_string(pulumi::pv::string("closed")))]).cast(), public: pulumi::ops::to_string(pulumi::pv::string("open")).cast(), public_data: pulumi_secret::types::DataArgs { private: pulumi::ops::to_string(pulumi::pv::string("closed")).cast(), public: pulumi::ops::to_string(pulumi::pv::string("open")).cast() } }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
