// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let plain_bool = ctx.config().require_bool("plainBool")?;
        let plain_number = ctx.config().require_number("plainNumber")?;
        let plain_integer = ctx.config().require_int("plainInteger")?;
        let plain_string = ctx.config().require_string("plainString")?;
        let plain_numeric_string = ctx.config().require_string("plainNumericString")?;
        let secret_number = pulumi::pv::secret(ctx.config().require_object("secretNumber")?);
        let secret_integer = pulumi::pv::secret(ctx.config().require_object("secretInteger")?);
        let secret_string = pulumi::pv::secret(ctx.config().require_object("secretString")?);
        let secret_numeric_string = pulumi::pv::secret(ctx.config().require_object("secretNumericString")?);
        let plain_values = pulumi_primitive::Resource::new(&ctx, "plainValues", pulumi_primitive::ResourceArgs { boolean: pulumi::ops::to_bool(plain_string.clone()).cast(), boolean_map: pulumi::pv::object(vec![("fromBool".to_string(), pulumi::ops::to_bool(plain_bool.clone())), ("fromString".to_string(), pulumi::ops::to_bool(plain_string.clone()))]).cast(), float: pulumi::ops::to_number(plain_integer.clone()).cast(), integer: pulumi::ops::to_int(plain_numeric_string.clone()).cast(), number_array: pulumi::pv::array(vec![pulumi::ops::to_number(plain_integer.clone()), pulumi::ops::to_number(plain_numeric_string.clone()), pulumi::ops::to_number(plain_number.clone())]).cast(), string: pulumi::ops::to_string(plain_number.clone()).cast() }, pulumi::ResourceOptions::default());
        let secret_values = pulumi_primitive::Resource::new(&ctx, "secretValues", pulumi_primitive::ResourceArgs { boolean: pulumi::ops::to_bool(secret_string.clone()).cast(), boolean_map: pulumi::pv::object(vec![("fromBool".to_string(), pulumi::ops::to_bool(plain_bool.clone())), ("fromString".to_string(), pulumi::ops::to_bool(plain_string.clone()))]).cast(), float: pulumi::ops::to_number(secret_integer.clone()).cast(), integer: pulumi::ops::to_int(secret_numeric_string.clone()).cast(), number_array: pulumi::pv::array(vec![pulumi::ops::to_number(plain_integer.clone()), pulumi::ops::to_number(plain_numeric_string.clone()), pulumi::ops::to_number(plain_number.clone())]).cast(), string: pulumi::ops::to_string(secret_number.clone()).cast() }, pulumi::ResourceOptions::default());
        let invoke_result = pulumi_primitive::invoke(&ctx, pulumi_primitive::InvokeArgs { boolean: pulumi::ops::to_bool(pulumi::ops::to_bool(plain_string.clone())).cast(), boolean_map: pulumi::pv::object(vec![("fromBool".to_string(), plain_bool.clone()), ("fromString".to_string(), pulumi::ops::to_bool(pulumi::ops::to_bool(plain_string.clone())))]).cast(), float: pulumi::ops::to_number(pulumi::ops::to_number(plain_integer.clone())).cast(), integer: pulumi::ops::to_int(pulumi::ops::to_int(plain_numeric_string.clone())).cast(), number_array: pulumi::pv::array(vec![pulumi::ops::to_number(pulumi::ops::to_number(plain_integer.clone())), pulumi::ops::to_number(pulumi::ops::to_number(plain_numeric_string.clone())), plain_number.clone()]).cast(), string: pulumi::ops::to_string(pulumi::ops::to_string(plain_bool.clone())).cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>();
        let invoke_values = pulumi_primitive::Resource::new(&ctx, "invokeValues", pulumi_primitive::ResourceArgs { boolean: pulumi::ops::to_bool(invoke_result.clone().index("boolean")).cast(), boolean_map: invoke_result.clone().index("booleanMap").cast(), float: pulumi::ops::to_number(invoke_result.clone().index("float")).cast(), integer: pulumi::ops::to_int(invoke_result.clone().index("integer")).cast(), number_array: invoke_result.clone().index("numberArray").cast(), string: pulumi::ops::to_string(invoke_result.clone().index("string")).cast() }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
