// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let input = ctx.config().require_string("input")?;
        let bytes = pulumi::pv::from_base64(input.clone());
        ctx.export("data", bytes.clone());
        ctx.export("roundtrip", pulumi::pv::to_base64(bytes.clone()));
        Ok(())
    });
}
