// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ExampleArgs {
    pub array_of_union_of: Option<pulumi::Output<std::vec::Vec<pulumi::PropertyValue>>>,
    pub union_of: Option<pulumi::Output<pulumi::PropertyValue>>,
}

impl ExampleArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.array_of_union_of {
            inputs.push(("arrayOfUnionOf".to_string(), v.cast()));
        }
        if let Some(v) = self.union_of {
            inputs.push(("unionOf".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Example {
    resource: pulumi::Resource,
}

impl Example {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ExampleArgs, options: pulumi::ResourceOptions) -> Example {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "discriminated-union:index:Example".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "31.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Example { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn array_of_union_of(&self) -> pulumi::Output<Option<std::vec::Vec<pulumi::PropertyValue>>> {
        self.resource.output("arrayOfUnionOf").cast()
    }

    pub fn union_of(&self) -> pulumi::Output<Option<pulumi::PropertyValue>> {
        self.resource.output("unionOf").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:discriminated-union".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "31.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct VariantOneArgs {
        pub discriminant_kind: pulumi::Output<std::string::String>,
        pub field1: Option<pulumi::Output<std::string::String>>,
    }

    impl VariantOneArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.discriminant_kind;
                inputs.push(("discriminantKind".to_string(), v.cast()));
            }
            if let Some(v) = self.field1 {
                inputs.push(("field1".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug)]
    pub struct VariantTwoArgs {
        pub discriminant_kind: pulumi::Output<std::string::String>,
        pub field2: Option<pulumi::Output<std::string::String>>,
    }

    impl VariantTwoArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.discriminant_kind;
                inputs.push(("discriminantKind".to_string(), v.cast()));
            }
            if let Some(v) = self.field2 {
                inputs.push(("field2".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug)]
    pub struct VariantOne {
        pub discriminant_kind: std::string::String,
        pub field1: Option<std::string::String>,
    }

    impl pulumi::FromPropertyValue for VariantOne {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(VariantOne {
                discriminant_kind: pulumi::convert::from_property_map(&m, "discriminantKind")?,
                field1: pulumi::convert::from_property_map(&m, "field1")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct VariantTwo {
        pub discriminant_kind: std::string::String,
        pub field2: Option<std::string::String>,
    }

    impl pulumi::FromPropertyValue for VariantTwo {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(VariantTwo {
                discriminant_kind: pulumi::convert::from_property_map(&m, "discriminantKind")?,
                field2: pulumi::convert::from_property_map(&m, "field2")?,
            })
        }
    }
}
