// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:replaceonchanges".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "25.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct ResourceAArgs {
    pub replace_prop: Option<pulumi::Output<bool>>,
    pub value: pulumi::Output<bool>,
}

impl ResourceAArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.replace_prop {
            inputs.push(("replaceProp".to_string(), v.cast()));
        }
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ResourceA {
    resource: pulumi::Resource,
}

impl ResourceA {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceAArgs, options: pulumi::ResourceOptions) -> ResourceA {
        let mut options = options;
        options.replace_on_changes.push("replaceProp".to_string());
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "replaceonchanges:index:ResourceA".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "25.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ResourceA { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn replace_prop(&self) -> pulumi::Output<Option<bool>> {
        self.resource.output("replaceProp").cast()
    }

    pub fn value(&self) -> pulumi::Output<bool> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ResourceBArgs {
    pub value: pulumi::Output<bool>,
}

impl ResourceBArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ResourceB {
    resource: pulumi::Resource,
}

impl ResourceB {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceBArgs, options: pulumi::ResourceOptions) -> ResourceB {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "replaceonchanges:index:ResourceB".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "25.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ResourceB { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<bool> {
        self.resource.output("value").cast()
    }
}

