// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let provider = pulumi_simple::Provider::new(&ctx, "provider", pulumi_simple::ProviderArgs {  }, pulumi::ResourceOptions::default());
        let parent1 = pulumi_simple::Resource::new(&ctx, "parent1", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { provider: Some(provider.pulumi_resource().clone()), ..Default::default() });
        let child1 = pulumi_simple::Resource::new(&ctx, "child1", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { parent: Some(parent1.pulumi_resource().clone()), ..Default::default() });
        let orphan1 = pulumi_simple::Resource::new(&ctx, "orphan1", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let parent2 = pulumi_simple::Resource::new(&ctx, "parent2", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { protect: Some(true), retain_on_delete: Some(true), ..Default::default() });
        let child2 = pulumi_simple::Resource::new(&ctx, "child2", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { parent: Some(parent2.pulumi_resource().clone()), ..Default::default() });
        let child3 = pulumi_simple::Resource::new(&ctx, "child3", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { parent: Some(parent2.pulumi_resource().clone()), protect: Some(false), retain_on_delete: Some(false), ..Default::default() });
        let orphan2 = pulumi_simple::Resource::new(&ctx, "orphan2", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
