// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:union".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "18.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct EnumOutputArgs {
    pub name: pulumi::Output<std::string::String>,
}

impl EnumOutputArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.name;
            inputs.push(("name".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct EnumOutput {
    resource: pulumi::Resource,
}

impl EnumOutput {
    pub fn new(ctx: &pulumi::Context, name: &str, args: EnumOutputArgs, options: pulumi::ResourceOptions) -> EnumOutput {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "union:index:EnumOutput".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "18.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        EnumOutput { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn name(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("name").cast()
    }

    pub fn r#type(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("type").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ExampleArgs {
    pub map_map_union_property: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::collections::BTreeMap<std::string::String, pulumi::PropertyValue>>>>,
    pub string_enum_union_list_property: Option<pulumi::Output<std::vec::Vec<pulumi::PropertyValue>>>,
    pub string_or_integer_property: Option<pulumi::Output<pulumi::PropertyValue>>,
    pub typed_enum_property: Option<pulumi::Output<pulumi::PropertyValue>>,
}

impl ExampleArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.map_map_union_property {
            inputs.push(("mapMapUnionProperty".to_string(), v.cast()));
        }
        if let Some(v) = self.string_enum_union_list_property {
            inputs.push(("stringEnumUnionListProperty".to_string(), v.cast()));
        }
        if let Some(v) = self.string_or_integer_property {
            inputs.push(("stringOrIntegerProperty".to_string(), v.cast()));
        }
        if let Some(v) = self.typed_enum_property {
            inputs.push(("typedEnumProperty".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Example {
    resource: pulumi::Resource,
}

impl Example {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ExampleArgs, options: pulumi::ResourceOptions) -> Example {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "union:index:Example".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "18.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Example { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn map_map_union_property(&self) -> pulumi::Output<Option<std::collections::BTreeMap<std::string::String, std::collections::BTreeMap<std::string::String, pulumi::PropertyValue>>>> {
        self.resource.output("mapMapUnionProperty").cast()
    }

    pub fn string_enum_union_list_property(&self) -> pulumi::Output<Option<std::vec::Vec<pulumi::PropertyValue>>> {
        self.resource.output("stringEnumUnionListProperty").cast()
    }

    pub fn string_or_integer_property(&self) -> pulumi::Output<Option<pulumi::PropertyValue>> {
        self.resource.output("stringOrIntegerProperty").cast()
    }

    pub fn typed_enum_property(&self) -> pulumi::Output<Option<pulumi::PropertyValue>> {
        self.resource.output("typedEnumProperty").cast()
    }
}

