// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ResArrayArgs {
    pub value: pulumi::Output<bool>,
}

impl ResArrayArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ResArray {
    resource: pulumi::Resource,
}

impl ResArray {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResArrayArgs, options: pulumi::ResourceOptions) -> ResArray {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "names:index:ResArray".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "6.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ResArray { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<bool> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ResListArgs {
    pub value: pulumi::Output<bool>,
}

impl ResListArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ResList {
    resource: pulumi::Resource,
}

impl ResList {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResListArgs, options: pulumi::ResourceOptions) -> ResList {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "names:index:ResList".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "6.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ResList { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<bool> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ResMapArgs {
    pub value: pulumi::Output<bool>,
}

impl ResMapArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ResMap {
    resource: pulumi::Resource,
}

impl ResMap {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResMapArgs, options: pulumi::ResourceOptions) -> ResMap {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "names:index:ResMap".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "6.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ResMap { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<bool> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ResResourceArgs {
    pub value: pulumi::Output<bool>,
}

impl ResResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ResResource {
    resource: pulumi::Resource,
}

impl ResResource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResResourceArgs, options: pulumi::ResourceOptions) -> ResResource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "names:index:ResResource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "6.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ResResource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<bool> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:names".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "6.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

pub mod r#mod {
    #[derive(Clone, Debug)]
    pub struct ResArgs {
        pub value: pulumi::Output<bool>,
    }

    impl ResArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.value;
                inputs.push(("value".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone)]
    pub struct Res {
        resource: pulumi::Resource,
    }

    impl Res {
        pub fn new(ctx: &pulumi::Context, name: &str, args: ResArgs, options: pulumi::ResourceOptions) -> Res {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "names:mod:Res".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "6.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            Res { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<std::string::String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<std::string::String> {
            self.resource.id()
        }

        pub fn value(&self) -> pulumi::Output<bool> {
            self.resource.output("value").cast()
        }
    }
}

pub mod mod_nested {
    #[derive(Clone, Debug)]
    pub struct ResArgs {
        pub value: pulumi::Output<bool>,
    }

    impl ResArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.value;
                inputs.push(("value".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone)]
    pub struct Res {
        resource: pulumi::Resource,
    }

    impl Res {
        pub fn new(ctx: &pulumi::Context, name: &str, args: ResArgs, options: pulumi::ResourceOptions) -> Res {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "names:mod/nested:Res".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "6.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            Res { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<std::string::String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<std::string::String> {
            self.resource.id()
        }

        pub fn value(&self) -> pulumi::Output<bool> {
            self.resource.output("value").cast()
        }
    }
}

