// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        ctx.export("expandedMax", pulumi::pv::max(vec![pulumi::pv::array(vec![pulumi::pv::number(1.0), pulumi::pv::number(2.0), pulumi::pv::number(3.0)])]));
        Ok(())
    });
}
