// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let a_string = ctx.config().require_string("aString")?;
        ctx.export("lengthResult", pulumi::pv::length(a_string.clone()));
        ctx.export("splitResult", pulumi::pv::split(pulumi::pv::string("-"), a_string.clone()));
        ctx.export("joinResult", pulumi::pv::join(pulumi::pv::string("|"), pulumi::pv::split(pulumi::pv::string("-"), a_string.clone())));
        ctx.export("interpolateResult", pulumi::pv::concat(vec![pulumi::pv::string("prefix-"), a_string.clone()]));
        Ok(())
    });
}
