// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res = pulumi_plain::Resource::new(&ctx, "res", pulumi_plain::ResourceArgs { data: pulumi_plain::types::DataArgs { bool_array: vec![true, false], boolean: true, float: 4.5, inner_data: pulumi_plain::types::InnerDataArgs { bool_array: vec![false, true], boolean: false, float: 2.17, integer: -12, string: "Goodbye".to_string(), string_map: std::collections::BTreeMap::from([("two".to_string(), "turtle doves".to_string()), ("three".to_string(), "french hens".to_string())]) }, integer: 1024, string: "Hello".to_string(), string_map: std::collections::BTreeMap::from([("x".to_string(), "100".to_string()), ("y".to_string(), "200".to_string())]) }, data_list: Some(vec![pulumi_plain::types::InnerDataArgs { bool_array: vec![true], boolean: true, float: 3.14, integer: 42, string: "Plain".to_string(), string_map: std::collections::BTreeMap::from([("one".to_string(), "partridge".to_string())]) }]), non_plain_data: None }, pulumi::ResourceOptions::default());
        let empty_list_res = pulumi_plain::Resource::new(&ctx, "emptyListRes", pulumi_plain::ResourceArgs { data: pulumi_plain::types::DataArgs { bool_array: vec![], boolean: false, float: 0.0, inner_data: pulumi_plain::types::InnerDataArgs { bool_array: vec![], boolean: false, float: 0.0, integer: 0, string: "".to_string(), string_map: std::collections::BTreeMap::from([]) }, integer: 0, string: "".to_string(), string_map: std::collections::BTreeMap::from([]) }, data_list: Some(vec![]), non_plain_data: None }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
