// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:camelNames".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "19.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

pub mod cool_module {
    #[derive(Clone, Debug)]
    pub struct SomeResourceArgs {
        pub resource_name: Option<pulumi::Output<std::string::String>>,
        pub the_input: pulumi::Output<bool>,
    }

    impl SomeResourceArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.resource_name {
                inputs.push(("resourceName".to_string(), v.cast()));
            }
            {
                let v = self.the_input;
                inputs.push(("theInput".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone)]
    pub struct SomeResource {
        resource: pulumi::Resource,
    }

    impl SomeResource {
        pub fn new(ctx: &pulumi::Context, name: &str, args: SomeResourceArgs, options: pulumi::ResourceOptions) -> SomeResource {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "camelNames:CoolModule:SomeResource".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "19.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            SomeResource { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<std::string::String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<std::string::String> {
            self.resource.id()
        }

        pub fn resource_name(&self) -> pulumi::Output<Option<std::string::String>> {
            self.resource.output("resourceName").cast()
        }

        pub fn the_output(&self) -> pulumi::Output<bool> {
            self.resource.output("theOutput").cast()
        }
    }
}

