// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res = ctx.read_resource("read:index:Resource", "res", pulumi::pv::string("existing-id"), vec![("lookup".to_string(), pulumi::pv::string("existing-key"))], "39.0.0", pulumi::ResourceOptions::default());
        ctx.export("resourceId", res.id().cast::<pulumi::PropertyValue>());
        ctx.export("resourceUrn", res.urn().cast::<pulumi::PropertyValue>());
        ctx.export("lookup", res.output("lookup"));
        ctx.export("value", res.output("value"));
        Ok(())
    });
}
