// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let block_1 = pulumi_sync::Block::new(&ctx, "block-1", pulumi_sync::BlockArgs {  }, pulumi::ResourceOptions::default());
        let block_2 = pulumi_sync::Block::new(&ctx, "block-2", pulumi_sync::BlockArgs {  }, pulumi::ResourceOptions::default());
        let block_3 = pulumi_sync::Block::new(&ctx, "block-3", pulumi_sync::BlockArgs {  }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
