// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        ctx.export("stackOutput", pulumi::pv::string(ctx.stack()));
        ctx.export("projectOutput", pulumi::pv::string(ctx.project()));
        ctx.export("organizationOutput", pulumi::pv::string(ctx.organization()));
        Ok(())
    });
}
