// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let ass = pulumi_asset_archive::AssetResource::new(&ctx, "ass", pulumi_asset_archive::AssetResourceArgs { value: pulumi::pv::file_asset(pulumi::pv::string("../test.txt")).cast() }, pulumi::ResourceOptions::default());
        let arc = pulumi_asset_archive::ArchiveResource::new(&ctx, "arc", pulumi_asset_archive::ArchiveResourceArgs { value: pulumi::pv::file_archive(pulumi::pv::string("../archive.tar")).cast() }, pulumi::ResourceOptions::default());
        let dir = pulumi_asset_archive::ArchiveResource::new(&ctx, "dir", pulumi_asset_archive::ArchiveResourceArgs { value: pulumi::pv::file_archive(pulumi::pv::string("../folder")).cast() }, pulumi::ResourceOptions::default());
        let assarc = pulumi_asset_archive::ArchiveResource::new(&ctx, "assarc", pulumi_asset_archive::ArchiveResourceArgs { value: pulumi::pv::asset_archive(vec![("string".to_string(), pulumi::pv::string_asset(pulumi::pv::string("file contents"))), ("file".to_string(), pulumi::pv::file_asset(pulumi::pv::string("../test.txt"))), ("folder".to_string(), pulumi::pv::file_archive(pulumi::pv::string("../folder"))), ("archive".to_string(), pulumi::pv::file_archive(pulumi::pv::string("../archive.tar")))]).cast() }, pulumi::ResourceOptions::default());
        let remoteass = pulumi_asset_archive::AssetResource::new(&ctx, "remoteass", pulumi_asset_archive::AssetResourceArgs { value: pulumi::pv::remote_asset(pulumi::pv::string("https://raw.githubusercontent.com/pulumi/pulumi/7b0eb7fb10694da2f31c0d15edf671df843e0d4c/cmd/pulumi-test-language/tests/testdata/l2-resource-asset-archive/test.txt")).cast() }, pulumi::ResourceOptions::default());
        let remotearc = pulumi_asset_archive::ArchiveResource::new(&ctx, "remotearc", pulumi_asset_archive::ArchiveResourceArgs { value: pulumi::pv::remote_archive(pulumi::pv::string("https://raw.githubusercontent.com/pulumi/pulumi/7b0eb7fb10694da2f31c0d15edf671df843e0d4c/cmd/pulumi-test-language/tests/testdata/l2-resource-asset-archive/archive.tar")).cast() }, pulumi::ResourceOptions::default());
        ctx.export("assetOutput", pulumi::pv::file_asset(pulumi::pv::string("../test.txt")));
        ctx.export("archiveOutput", pulumi::pv::file_archive(pulumi::pv::string("../archive.tar")));
        ctx.export("assetList", pulumi::pv::array(vec![pulumi::pv::file_asset(pulumi::pv::string("../test.txt")), pulumi::pv::string_asset(pulumi::pv::string("file contents"))]));
        ctx.export("archiveList", pulumi::pv::array(vec![pulumi::pv::file_archive(pulumi::pv::string("../archive.tar")), pulumi::pv::file_archive(pulumi::pv::string("../folder"))]));
        ctx.export("assetMap", pulumi::pv::object(vec![("file".to_string(), pulumi::pv::file_asset(pulumi::pv::string("../test.txt"))), ("string".to_string(), pulumi::pv::string_asset(pulumi::pv::string("file contents")))]));
        ctx.export("archiveMap", pulumi::pv::object(vec![("tar".to_string(), pulumi::pv::file_archive(pulumi::pv::string("../archive.tar"))), ("folder".to_string(), pulumi::pv::file_archive(pulumi::pv::string("../folder")))]));
        Ok(())
    });
}
