// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let a_map = ctx.config().require_object("aMap")?;
        ctx.export("theMap", pulumi::pv::object(vec![("a".to_string(), pulumi::ops::add(a_map.clone().index("a"), pulumi::pv::number(1.0))), ("b".to_string(), pulumi::ops::add(a_map.clone().index("b"), pulumi::pv::number(1.0)))]));
        let an_object = ctx.config().require_object("anObject")?;
        ctx.export("theObject", an_object.clone().index("prop").index(0usize));
        let any_object = ctx.config().require_object("anyObject")?;
        ctx.export("theThing", pulumi::ops::add(any_object.clone().index("a"), any_object.clone().index("b")));
        let optional_untyped_object = ctx.config().get_object_or("optionalUntypedObject", pulumi::PropertyValue::Object(std::collections::BTreeMap::from([("key".to_string(), pulumi::PropertyValue::String("value".to_string()))])));
        ctx.export("defaultUntypedObject", optional_untyped_object.clone());
        let optional_list = ctx.config().get_object_or("optionalList", pulumi::PropertyValue::Null);
        let optional_map = ctx.config().get_object_or("optionalMap", pulumi::PropertyValue::Null);
        let optional_object = ctx.config().get_object_or("optionalObject", pulumi::PropertyValue::Null);
        ctx.export("optionalList", pulumi::ops::cond(pulumi::ops::eq(optional_list.clone(), pulumi::pv::null()), pulumi::pv::string("null"), pulumi::pv::to_json(optional_list.clone())));
        ctx.export("optionalMap", pulumi::ops::cond(pulumi::ops::eq(optional_map.clone(), pulumi::pv::null()), pulumi::pv::string("null"), pulumi::pv::to_json(optional_map.clone())));
        ctx.export("optionalObject", pulumi::ops::cond(pulumi::ops::eq(optional_object.clone(), pulumi::pv::null()), pulumi::pv::string("null"), pulumi::pv::to_json(optional_object.clone())));
        Ok(())
    });
}
