// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let plain_bool = ctx.config().require_bool("plainBool")?;
        let plain_number = ctx.config().require_number("plainNumber")?;
        let plain_integer = ctx.config().require_int("plainInteger")?;
        let plain_string = ctx.config().require_string("plainString")?;
        let secret_bool = pulumi::pv::secret(ctx.config().require_object("secretBool")?);
        let secret_number = pulumi::pv::secret(ctx.config().require_object("secretNumber")?);
        let secret_integer = pulumi::pv::secret(ctx.config().require_object("secretInteger")?);
        let secret_string = pulumi::pv::secret(ctx.config().require_object("secretString")?);
        let plain = pulumi_primitive::Resource::new(&ctx, "plain", pulumi_primitive::ResourceArgs { boolean: pulumi::ops::to_bool(plain_bool.clone()).cast(), boolean_map: pulumi::pv::object(vec![("t".to_string(), pulumi::ops::to_bool(pulumi::pv::bool(true))), ("f".to_string(), pulumi::ops::to_bool(pulumi::pv::bool(false)))]).cast(), float: pulumi::ops::to_number(plain_number.clone()).cast(), integer: pulumi::ops::to_int(plain_integer.clone()).cast(), number_array: pulumi::pv::array(vec![pulumi::ops::to_number(pulumi::pv::number(-1.0)), pulumi::ops::to_number(pulumi::pv::number(0.0)), pulumi::ops::to_number(pulumi::pv::number(1.0))]).cast(), string: pulumi::ops::to_string(plain_string.clone()).cast() }, pulumi::ResourceOptions::default());
        let secret = pulumi_primitive::Resource::new(&ctx, "secret", pulumi_primitive::ResourceArgs { boolean: pulumi::ops::to_bool(secret_bool.clone()).cast(), boolean_map: pulumi::pv::object(vec![("t".to_string(), pulumi::ops::to_bool(pulumi::pv::bool(true))), ("f".to_string(), pulumi::ops::to_bool(pulumi::pv::bool(false)))]).cast(), float: pulumi::ops::to_number(secret_number.clone()).cast(), integer: pulumi::ops::to_int(secret_integer.clone()).cast(), number_array: pulumi::pv::array(vec![pulumi::ops::to_number(pulumi::pv::number(-2.0)), pulumi::ops::to_number(pulumi::pv::number(0.0)), pulumi::ops::to_number(pulumi::pv::number(2.0))]).cast(), string: pulumi::ops::to_string(secret_string.clone()).cast() }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
