// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let prov = pulumi_config_enum::Provider::new(&ctx, "prov", pulumi_config_enum::ProviderArgs { a_enum: pulumi::pv::string("two").cast(), a_string: pulumi::ops::to_string(pulumi::pv::string("hello")).cast() }, pulumi::ResourceOptions::default());
        let res = pulumi_config_enum::Resource::new(&ctx, "res", pulumi_config_enum::ResourceArgs { the_enum: prov.a_enum().cast::<pulumi::PropertyValue>().cast(), the_string: pulumi::ops::to_string(prov.a_string().cast::<pulumi::PropertyValue>()).cast() }, pulumi::ResourceOptions { provider: Some(prov.pulumi_resource().clone()), ..Default::default() });
        Ok(())
    });
}
