// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let target = pulumi_component::ComponentCustomRefOutput::new(&ctx, "target", pulumi_component::ComponentCustomRefOutputArgs { value: pulumi::ops::to_string(pulumi::pv::string("checked")).cast() }, pulumi::ResourceOptions::default());
        let data = pulumi_component::identity(&ctx, pulumi_component::IdentityArgs { input: pulumi::pv::string("reachable").cast() }, pulumi::InvokeOptions { depends_on: vec![target.pulumi_resource().clone()], ..Default::default() }).cast::<pulumi::PropertyValue>();
        ctx.export("echoed", data.clone().index("result"));
        Ok(())
    });
}
