// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct StringArgs {
    pub value: pulumi::Output<std::string::String>,
}

impl StringArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct String {
    resource: pulumi::Resource,
}

impl String {
    pub fn new(ctx: &pulumi::Context, name: &str, args: StringArgs, options: pulumi::ResourceOptions) -> String {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "large:index:String".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "4.3.2".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        String { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:large".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "4.3.2".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

