// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let create_timeout = ctx.config().require_string("createTimeout")?;
        let no_timeouts = pulumi_simple::Resource::new(&ctx, "noTimeouts", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let create_only = pulumi_simple::Resource::new(&ctx, "createOnly", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { create: Some(pulumi::pv::string("5m")), ..Default::default() }), ..Default::default() });
        let update_only = pulumi_simple::Resource::new(&ctx, "updateOnly", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { update: Some(pulumi::pv::string("10m")), ..Default::default() }), ..Default::default() });
        let delete_only = pulumi_simple::Resource::new(&ctx, "deleteOnly", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { delete: Some(pulumi::pv::string("3m")), ..Default::default() }), ..Default::default() });
        let read_only = pulumi_simple::Resource::new(&ctx, "readOnly", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { read: Some(pulumi::pv::string("9m")), ..Default::default() }), ..Default::default() });
        let all_timeouts = pulumi_simple::Resource::new(&ctx, "allTimeouts", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { create: Some(pulumi::pv::string("2m")), update: Some(pulumi::pv::string("4m")), delete: Some(pulumi::pv::string("1m")), read: Some(pulumi::pv::string("5m")), ..Default::default() }), ..Default::default() });
        let config_timeout = pulumi_simple::Resource::new(&ctx, "configTimeout", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { custom_timeouts: Some(pulumi::CustomTimeouts { create: Some(create_timeout.clone()), ..Default::default() }), ..Default::default() });
        Ok(())
    });
}
