// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let version = ctx.config().require_string("version")?;
        ctx.require_pulumi_version(version.clone()).await?;
        Ok(())
    });
}
