// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ComplexResourceArgs {
    pub value: pulumi::Output<f64>,
}

impl ComplexResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ComplexResource {
    resource: pulumi::Resource,
}

impl ComplexResource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ComplexResourceArgs, options: pulumi::ResourceOptions) -> ComplexResource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "output:index:ComplexResource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "23.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ComplexResource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn output_array(&self) -> pulumi::Output<std::vec::Vec<std::string::String>> {
        self.resource.output("outputArray").cast()
    }

    pub fn output_map(&self) -> pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>> {
        self.resource.output("outputMap").cast()
    }

    pub fn output_object(&self) -> pulumi::Output<crate::types::Data> {
        self.resource.output("outputObject").cast()
    }

    pub fn value(&self) -> pulumi::Output<f64> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ResourceArgs {
    pub value: pulumi::Output<f64>,
}

impl ResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Resource {
    resource: pulumi::Resource,
}

impl Resource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
        let mut options = options;
        options.additional_secret_outputs.push("secretOutput".to_string());
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "output:index:Resource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "23.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Resource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn output(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("output").cast()
    }

    pub fn secret_output(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("secretOutput").as_secret().cast()
    }

    pub fn value(&self) -> pulumi::Output<f64> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
    pub elide_unknowns: Option<pulumi::Output<bool>>,
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.elide_unknowns {
            inputs.push(("elideUnknowns".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:output".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "23.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct Data {
        pub output: std::string::String,
    }

    impl pulumi::FromPropertyValue for Data {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Data {
                output: pulumi::convert::from_property_map(&m, "output")?,
            })
        }
    }
}
