// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ResourceArgs {
    pub the_enum: pulumi::Output<std::string::String>,
    pub the_string: pulumi::Output<std::string::String>,
}

impl ResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.the_enum;
            inputs.push(("theEnum".to_string(), v.cast()));
        }
        {
            let v = self.the_string;
            inputs.push(("theString".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Resource {
    resource: pulumi::Resource,
}

impl Resource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "config-enum:index:Resource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "41.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Resource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn the_enum(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("theEnum").cast()
    }

    pub fn the_string(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("theString").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ProviderArgs {
    pub a_enum: pulumi::Output<std::string::String>,
    pub a_string: pulumi::Output<std::string::String>,
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.a_enum;
            inputs.push(("aEnum".to_string(), v.cast()));
        }
        {
            let v = self.a_string;
            inputs.push(("aString".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:config-enum".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "41.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn a_enum(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("aEnum").cast()
    }

    pub fn a_string(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("aString").cast()
    }
}

