// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let a_list = ctx.config().require_object("aList")?;
        let single_or_none_list = ctx.config().require_object("singleOrNoneList")?;
        let a_string = ctx.config().require_string("aString")?;
        ctx.export("elementOutput1", pulumi::pv::element(a_list.clone(), pulumi::pv::number(1.0)));
        ctx.export("elementOutput2", pulumi::pv::element(a_list.clone(), pulumi::pv::number(2.0)));
        ctx.export("joinOutput", pulumi::pv::join(pulumi::pv::string("|"), a_list.clone()));
        ctx.export("lengthOutput", pulumi::pv::length(a_list.clone()));
        ctx.export("splitOutput", pulumi::pv::split(pulumi::pv::string("-"), a_string.clone()));
        ctx.export("singleOrNoneOutput", pulumi::pv::array(vec![pulumi::pv::single_or_none(single_or_none_list.clone())]));
        Ok(())
    });
}
