// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let a_secret = pulumi::pv::secret(ctx.config().require_object("aSecret")?);
        let not_secret = ctx.config().require_string("notSecret")?;
        ctx.export("roundtripSecret", a_secret.clone());
        ctx.export("roundtripNotSecret", not_secret.clone());
        ctx.export("double", pulumi::pv::secret(a_secret.clone()));
        ctx.export("open", pulumi::pv::unsecret(a_secret.clone()));
        ctx.export("close", pulumi::pv::secret(not_secret.clone()));
        Ok(())
    });
}
