// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let input = ctx.config().require_string("input")?;
        let hash = pulumi::pv::sha1_hex(input.clone());
        ctx.export("hash", hash.clone());
        Ok(())
    });
}
