// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let a_number = ctx.config().require_number("aNumber")?;
        ctx.export("theNumber", pulumi::ops::add(a_number.clone(), pulumi::pv::number(1.25)));
        let optional_number = ctx.config().get_number_or("optionalNumber", pulumi::PropertyValue::Number(41.5));
        ctx.export("defaultNumber", pulumi::ops::add(optional_number.clone(), pulumi::pv::number(1.2)));
        let an_int = ctx.config().require_int("anInt")?;
        ctx.export("theInteger", pulumi::ops::add(an_int.clone(), pulumi::pv::number(4.0)));
        let optional_int = ctx.config().get_int_or("optionalInt", pulumi::PropertyValue::Number(1.0));
        ctx.export("defaultInteger", pulumi::ops::add(optional_int.clone(), pulumi::pv::number(2.0)));
        let a_string = ctx.config().require_string("aString")?;
        ctx.export("theString", pulumi::pv::concat(vec![a_string.clone(), pulumi::pv::string(" World")]));
        let optional_string = ctx.config().get_string_or("optionalString", pulumi::PropertyValue::String("defaultStringValue".to_string()));
        ctx.export("defaultString", optional_string.clone());
        let a_bool = ctx.config().require_bool("aBool")?;
        ctx.export("theBool", pulumi::ops::and(pulumi::ops::not(a_bool.clone()), pulumi::pv::bool(true)));
        let optional_bool = ctx.config().get_bool_or("optionalBool", pulumi::PropertyValue::Bool(false));
        ctx.export("defaultBool", optional_bool.clone());
        Ok(())
    });
}
