// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ComponentCallableArgs {
    pub value: pulumi::Output<std::string::String>,
}

impl ComponentCallableArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ComponentCallable {
    resource: pulumi::Resource,
}

impl ComponentCallable {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ComponentCallableArgs, options: pulumi::ResourceOptions) -> ComponentCallable {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "component:index:ComponentCallable".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "13.3.7".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ComponentCallable { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ComponentCustomRefInputOutputArgs {
    pub input_ref: pulumi::Output<pulumi::PropertyValue>,
}

impl ComponentCustomRefInputOutputArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.input_ref;
            inputs.push(("inputRef".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ComponentCustomRefInputOutput {
    resource: pulumi::Resource,
}

impl ComponentCustomRefInputOutput {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ComponentCustomRefInputOutputArgs, options: pulumi::ResourceOptions) -> ComponentCustomRefInputOutput {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "component:index:ComponentCustomRefInputOutput".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "13.3.7".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ComponentCustomRefInputOutput { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn input_ref(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.resource.output("inputRef").cast()
    }

    pub fn output_ref(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.resource.output("outputRef").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ComponentCustomRefOutputArgs {
    pub value: pulumi::Output<std::string::String>,
}

impl ComponentCustomRefOutputArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ComponentCustomRefOutput {
    resource: pulumi::Resource,
}

impl ComponentCustomRefOutput {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ComponentCustomRefOutputArgs, options: pulumi::ResourceOptions) -> ComponentCustomRefOutput {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "component:index:ComponentCustomRefOutput".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "13.3.7".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ComponentCustomRefOutput { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn r#ref(&self) -> pulumi::Output<pulumi::PropertyValue> {
        self.resource.output("ref").cast()
    }

    pub fn value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ComponentForeignChildArgs {
    pub value: pulumi::Output<bool>,
}

impl ComponentForeignChildArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ComponentForeignChild {
    resource: pulumi::Resource,
}

impl ComponentForeignChild {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ComponentForeignChildArgs, options: pulumi::ResourceOptions) -> ComponentForeignChild {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "component:index:ComponentForeignChild".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "13.3.7".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ComponentForeignChild { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn value(&self) -> pulumi::Output<bool> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug)]
pub struct CustomArgs {
    pub value: pulumi::Output<std::string::String>,
}

impl CustomArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Custom {
    resource: pulumi::Resource,
}

impl Custom {
    pub fn new(ctx: &pulumi::Context, name: &str, args: CustomArgs, options: pulumi::ResourceOptions) -> Custom {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "component:index:Custom".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "13.3.7".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Custom { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:component".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "13.3.7".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct IdentityArgs {
    pub input: pulumi::Output<std::string::String>,
}

impl IdentityArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.input;
            inputs.push(("input".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn identity(ctx: &pulumi::Context, args: IdentityArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::IdentityResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "13.3.7".to_string();
    }
    ctx.invoke("component:index:identity", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct IdentityResult {
        pub result: std::string::String,
    }

    impl pulumi::FromPropertyValue for IdentityResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(IdentityResult {
                result: pulumi::convert::from_property_map(&m, "result")?,
            })
        }
    }
}
