// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res = pulumi_large::String::new(&ctx, "res", pulumi_large::StringArgs { value: pulumi::ops::to_string(pulumi::pv::string("hello world")).cast() }, pulumi::ResourceOptions::default());
        ctx.export("output", res.value().cast::<pulumi::PropertyValue>());
        Ok(())
    });
}
