// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res_explicit = pulumi_primitive_defaults::Resource::new(&ctx, "resExplicit", pulumi_primitive_defaults::ResourceArgs { boolean: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()), float: Some(pulumi::ops::to_number(pulumi::pv::number(3.14)).cast()), integer: Some(pulumi::ops::to_int(pulumi::pv::number(42.0)).cast()), string: Some(pulumi::ops::to_string(pulumi::pv::string("hello")).cast()) }, pulumi::ResourceOptions::default());
        let res_defaulted = pulumi_primitive_defaults::Resource::new(&ctx, "resDefaulted", pulumi_primitive_defaults::ResourceArgs { boolean: None, float: None, integer: None, string: None }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
