// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let first_resource = pulumi_keywords::SomeResource::new(&ctx, "firstResource", pulumi_keywords::SomeResourceArgs { builtins: pulumi::ops::to_string(pulumi::pv::string("builtins")).cast(), lambda: pulumi::ops::to_string(pulumi::pv::string("lambda")).cast(), property: pulumi::ops::to_string(pulumi::pv::string("property")).cast() }, pulumi::ResourceOptions::default());
        let second_resource = pulumi_keywords::SomeResource::new(&ctx, "secondResource", pulumi_keywords::SomeResourceArgs { builtins: pulumi::ops::to_string(first_resource.builtins().cast::<pulumi::PropertyValue>()).cast(), lambda: pulumi::ops::to_string(first_resource.lambda().cast::<pulumi::PropertyValue>()).cast(), property: pulumi::ops::to_string(first_resource.property().cast::<pulumi::PropertyValue>()).cast() }, pulumi::ResourceOptions::default());
        let lambda_module_resource = pulumi_keywords::lambda::SomeResource::new(&ctx, "lambdaModuleResource", pulumi_keywords::lambda::SomeResourceArgs { builtins: pulumi::ops::to_string(pulumi::pv::string("builtins")).cast(), lambda: pulumi::ops::to_string(pulumi::pv::string("lambda")).cast(), property: pulumi::ops::to_string(pulumi::pv::string("property")).cast() }, pulumi::ResourceOptions::default());
        let lambda_resource = pulumi_keywords::module::Lambda::new(&ctx, "lambdaResource", pulumi_keywords::module::LambdaArgs { builtins: pulumi::ops::to_string(pulumi::pv::string("builtins")).cast(), lambda: pulumi::ops::to_string(pulumi::pv::string("lambda")).cast(), property: pulumi::ops::to_string(pulumi::pv::string("property")).cast() }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
