// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ResourceArgs {
    pub boolean: Option<pulumi::Output<bool>>,
    pub float: Option<pulumi::Output<f64>>,
    pub integer: Option<pulumi::Output<i32>>,
    pub string: Option<pulumi::Output<std::string::String>>,
}

impl ResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.boolean {
            inputs.push(("boolean".to_string(), v.cast()));
        } else {
            inputs.push(("boolean".to_string(), pulumi::Output::from_value(pulumi::PropertyValue::Bool(false))));
        }
        if let Some(v) = self.float {
            inputs.push(("float".to_string(), v.cast()));
        } else {
            inputs.push(("float".to_string(), pulumi::Output::from_value(pulumi::PropertyValue::Number(0.5))));
        }
        if let Some(v) = self.integer {
            inputs.push(("integer".to_string(), v.cast()));
        } else {
            inputs.push(("integer".to_string(), pulumi::Output::from_value(pulumi::PropertyValue::Number(1.0))));
        }
        if let Some(v) = self.string {
            inputs.push(("string".to_string(), v.cast()));
        } else {
            inputs.push(("string".to_string(), pulumi::Output::from_value(pulumi::PropertyValue::String("default".to_string()))));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Resource {
    resource: pulumi::Resource,
}

impl Resource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "primitive-defaults:index:Resource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "8.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Resource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn boolean(&self) -> pulumi::Output<Option<bool>> {
        self.resource.output("boolean").cast()
    }

    pub fn float(&self) -> pulumi::Output<Option<f64>> {
        self.resource.output("float").cast()
    }

    pub fn integer(&self) -> pulumi::Output<Option<i32>> {
        self.resource.output("integer").cast()
    }

    pub fn string(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("string").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:primitive-defaults".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "8.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

