// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let explicit = pulumi_component::Provider::new(&ctx, "explicit", pulumi_component::ProviderArgs {  }, pulumi::ResourceOptions::default());
        let list = pulumi_component::ComponentCallable::new(&ctx, "list", pulumi_component::ComponentCallableArgs { value: pulumi::ops::to_string(pulumi::pv::string("value")).cast() }, pulumi::ResourceOptions { providers: vec![("component".to_string(), explicit.pulumi_resource().clone())], ..Default::default() });
        let map = pulumi_component::ComponentCallable::new(&ctx, "map", pulumi_component::ComponentCallableArgs { value: pulumi::ops::to_string(pulumi::pv::string("value")).cast() }, pulumi::ResourceOptions { providers: vec![("component".to_string(), explicit.pulumi_resource().clone())], ..Default::default() });
        Ok(())
    });
}
