// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let prov = pulumi_output::Provider::new(&ctx, "prov", pulumi_output::ProviderArgs { elide_unknowns: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()) }, pulumi::ResourceOptions::default());
        let unknown = pulumi_output::Resource::new(&ctx, "unknown", pulumi_output::ResourceArgs { value: pulumi::ops::to_number(pulumi::pv::number(1.0)).cast() }, pulumi::ResourceOptions { provider: Some(prov.pulumi_resource().clone()), ..Default::default() });
        let complex = pulumi_output::ComplexResource::new(&ctx, "complex", pulumi_output::ComplexResourceArgs { value: pulumi::ops::to_number(pulumi::pv::number(1.0)).cast() }, pulumi::ResourceOptions { provider: Some(prov.pulumi_resource().clone()), ..Default::default() });
        let res = pulumi_simple::Resource::new(&ctx, "res", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::ops::eq(unknown.output().cast::<pulumi::PropertyValue>(), pulumi::pv::string("hello"))).cast() }, pulumi::ResourceOptions::default());
        let res_array = pulumi_simple::Resource::new(&ctx, "resArray", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::ops::eq(complex.output_array().cast::<pulumi::PropertyValue>().index(0usize), pulumi::pv::string("hello"))).cast() }, pulumi::ResourceOptions::default());
        let res_map = pulumi_simple::Resource::new(&ctx, "resMap", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::ops::eq(complex.output_map().cast::<pulumi::PropertyValue>().index("x"), pulumi::pv::string("hello"))).cast() }, pulumi::ResourceOptions::default());
        let res_object = pulumi_simple::Resource::new(&ctx, "resObject", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::ops::eq(complex.output_object().cast::<pulumi::PropertyValue>().index("output"), pulumi::pv::string("hello"))).cast() }, pulumi::ResourceOptions::default());
        ctx.export("out", unknown.output().cast::<pulumi::PropertyValue>());
        ctx.export("outArray", complex.output_array().cast::<pulumi::PropertyValue>().index(0usize));
        ctx.export("outMap", complex.output_map().cast::<pulumi::PropertyValue>().index("x"));
        ctx.export("outObject", complex.output_object().cast::<pulumi::PropertyValue>().index("output"));
        Ok(())
    });
}
