// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let prov = pulumi_simple::Provider::new(&ctx, "prov", pulumi_simple::ProviderArgs {  }, pulumi::ResourceOptions::default());
        let res = pulumi_simple::Resource::new(&ctx, "res", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { provider: Some(prov.pulumi_resource().clone()), ..Default::default() });
        Ok(())
    });
}
