// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let r#ref = pulumi::StackReference::new(&ctx, "ref", pulumi::pv::string("organization/other/dev"), pulumi::ResourceOptions::default());
        ctx.export("plain", r#ref.get_output(pulumi::pv::string("plain")));
        ctx.export("secret", r#ref.get_output(pulumi::pv::string("secret")));
        ctx.export("secret_unsecret", pulumi::pv::unsecret(r#ref.get_output(pulumi::pv::string("secret"))));
        Ok(())
    });
}
