// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct DeluxeArgs {
    pub array_of_enum: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub holder: Option<crate::types::HolderArgs>,
    pub map_of_enum: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub number_enum: Option<pulumi::Output<f64>>,
    pub union_enum: Option<pulumi::Output<pulumi::PropertyValue>>,
    pub wordy_enum: Option<pulumi::Output<std::string::String>>,
}

impl DeluxeArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.array_of_enum {
            inputs.push(("arrayOfEnum".to_string(), v.cast()));
        }
        if let Some(v) = self.holder {
            inputs.push(("holder".to_string(), v.into_output()));
        }
        if let Some(v) = self.map_of_enum {
            inputs.push(("mapOfEnum".to_string(), v.cast()));
        }
        if let Some(v) = self.number_enum {
            inputs.push(("numberEnum".to_string(), v.cast()));
        }
        if let Some(v) = self.union_enum {
            inputs.push(("unionEnum".to_string(), v.cast()));
        }
        if let Some(v) = self.wordy_enum {
            inputs.push(("wordyEnum".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Deluxe {
    resource: pulumi::Resource,
}

impl Deluxe {
    pub fn new(ctx: &pulumi::Context, name: &str, args: DeluxeArgs, options: pulumi::ResourceOptions) -> Deluxe {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "enum:index:Deluxe".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "30.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Deluxe { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn array_of_enum(&self) -> pulumi::Output<Option<std::vec::Vec<std::string::String>>> {
        self.resource.output("arrayOfEnum").cast()
    }

    pub fn holder(&self) -> pulumi::Output<Option<crate::types::Holder>> {
        self.resource.output("holder").cast()
    }

    pub fn map_of_enum(&self) -> pulumi::Output<Option<std::collections::BTreeMap<std::string::String, i32>>> {
        self.resource.output("mapOfEnum").cast()
    }

    pub fn number_enum(&self) -> pulumi::Output<Option<f64>> {
        self.resource.output("numberEnum").cast()
    }

    pub fn union_enum(&self) -> pulumi::Output<Option<pulumi::PropertyValue>> {
        self.resource.output("unionEnum").cast()
    }

    pub fn wordy_enum(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("wordyEnum").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ResArgs {
    pub int_enum: Option<pulumi::Output<i32>>,
    pub string_enum: Option<pulumi::Output<std::string::String>>,
}

impl ResArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.int_enum {
            inputs.push(("intEnum".to_string(), v.cast()));
        }
        if let Some(v) = self.string_enum {
            inputs.push(("stringEnum".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Res {
    resource: pulumi::Resource,
}

impl Res {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResArgs, options: pulumi::ResourceOptions) -> Res {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "enum:index:Res".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "30.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Res { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn int_enum(&self) -> pulumi::Output<Option<i32>> {
        self.resource.output("intEnum").cast()
    }

    pub fn string_enum(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("stringEnum").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:enum".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "30.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

pub mod r#mod {
    #[derive(Clone, Debug, Default)]
    pub struct ResArgs {
        pub int_enum: Option<pulumi::Output<i32>>,
        pub string_enum: Option<pulumi::Output<std::string::String>>,
    }

    impl ResArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.int_enum {
                inputs.push(("intEnum".to_string(), v.cast()));
            }
            if let Some(v) = self.string_enum {
                inputs.push(("stringEnum".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone)]
    pub struct Res {
        resource: pulumi::Resource,
    }

    impl Res {
        pub fn new(ctx: &pulumi::Context, name: &str, args: ResArgs, options: pulumi::ResourceOptions) -> Res {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "enum:mod:Res".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "30.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            Res { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<std::string::String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<std::string::String> {
            self.resource.id()
        }

        pub fn int_enum(&self) -> pulumi::Output<Option<i32>> {
            self.resource.output("intEnum").cast()
        }

        pub fn string_enum(&self) -> pulumi::Output<Option<std::string::String>> {
            self.resource.output("stringEnum").cast()
        }
    }
}

pub mod mod_nested {
    #[derive(Clone, Debug, Default)]
    pub struct ResArgs {
        pub int_enum: Option<pulumi::Output<i32>>,
        pub string_enum: Option<pulumi::Output<std::string::String>>,
    }

    impl ResArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.int_enum {
                inputs.push(("intEnum".to_string(), v.cast()));
            }
            if let Some(v) = self.string_enum {
                inputs.push(("stringEnum".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone)]
    pub struct Res {
        resource: pulumi::Resource,
    }

    impl Res {
        pub fn new(ctx: &pulumi::Context, name: &str, args: ResArgs, options: pulumi::ResourceOptions) -> Res {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "enum:mod/nested:Res".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "30.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            Res { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<std::string::String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<std::string::String> {
            self.resource.id()
        }

        pub fn int_enum(&self) -> pulumi::Output<Option<i32>> {
            self.resource.output("intEnum").cast()
        }

        pub fn string_enum(&self) -> pulumi::Output<Option<std::string::String>> {
            self.resource.output("stringEnum").cast()
        }
    }
}

pub mod types {
    #[derive(Clone, Debug, Default)]
    pub struct HolderArgs {
        pub color: Option<pulumi::Output<std::string::String>>,
        pub size: Option<pulumi::Output<i32>>,
    }

    impl HolderArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.color {
                inputs.push(("color".to_string(), v.cast()));
            }
            if let Some(v) = self.size {
                inputs.push(("size".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug)]
    pub struct Holder {
        pub color: Option<std::string::String>,
        pub size: Option<i32>,
    }

    impl pulumi::FromPropertyValue for Holder {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Holder {
                color: pulumi::convert::from_property_map(&m, "color")?,
                size: pulumi::convert::from_property_map(&m, "size")?,
            })
        }
    }
}
