// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let my_stash = ctx.register_resource(pulumi::RegisterRequest { type_: "pulumi:index:Stash".to_string(), name: "myStash".to_string(), custom: true, remote: false, version: String::new(), plugin_download_url: String::new(), inputs: vec![("input".to_string(), pulumi::pv::string("ignored"))], options: pulumi::ResourceOptions::default() });
        ctx.export("stashInput", my_stash.output("input"));
        ctx.export("stashOutput", my_stash.output("output"));
        Ok(())
    });
}
