// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let file_content = pulumi::pv::read_file(pulumi::pv::string("testfile.txt"));
        let file_b64 = pulumi::pv::file_base64(pulumi::pv::string("testfile.txt"));
        let file_sha = pulumi::pv::file_base64_sha256(pulumi::pv::string("testfile.txt"));
        ctx.export("fileContent", file_content.clone());
        ctx.export("fileB64", file_b64.clone());
        ctx.export("fileSha", file_sha.clone());
        Ok(())
    });
}
