// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let schema_replace = pulumi_replaceonchanges::ResourceA::new(&ctx, "schemaReplace", pulumi_replaceonchanges::ResourceAArgs { replace_prop: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()), value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let option_replace = pulumi_replaceonchanges::ResourceB::new(&ctx, "optionReplace", pulumi_replaceonchanges::ResourceBArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { replace_on_changes: vec!["value".to_string()], ..Default::default() });
        let both_replace_value = pulumi_replaceonchanges::ResourceA::new(&ctx, "bothReplaceValue", pulumi_replaceonchanges::ResourceAArgs { replace_prop: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()), value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { replace_on_changes: vec!["value".to_string()], ..Default::default() });
        let both_replace_prop = pulumi_replaceonchanges::ResourceA::new(&ctx, "bothReplaceProp", pulumi_replaceonchanges::ResourceAArgs { replace_prop: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()), value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { replace_on_changes: vec!["value".to_string()], ..Default::default() });
        let regular_update = pulumi_replaceonchanges::ResourceB::new(&ctx, "regularUpdate", pulumi_replaceonchanges::ResourceBArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let no_change = pulumi_replaceonchanges::ResourceB::new(&ctx, "noChange", pulumi_replaceonchanges::ResourceBArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { replace_on_changes: vec!["value".to_string()], ..Default::default() });
        let wrong_prop_change = pulumi_replaceonchanges::ResourceA::new(&ctx, "wrongPropChange", pulumi_replaceonchanges::ResourceAArgs { replace_prop: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()), value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { replace_on_changes: vec!["value".to_string()], ..Default::default() });
        let multiple_prop_replace = pulumi_replaceonchanges::ResourceA::new(&ctx, "multiplePropReplace", pulumi_replaceonchanges::ResourceAArgs { replace_prop: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()), value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { replace_on_changes: vec!["value".to_string(), "replaceProp".to_string()], ..Default::default() });
        Ok(())
    });
}
