// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let first = pulumi_constant::Resource::new(&ctx, "first", pulumi_constant::ResourceArgs { kind: pulumi::pv::string("Constant").cast() }, pulumi::ResourceOptions::default());
        ctx.export("kind", first.kind().cast::<pulumi::PropertyValue>());
        Ok(())
    });
}
