// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ResourceArgs {
    pub data: crate::types::DataArgs,
    pub optional_data: Option<crate::types::DataArgs>,
}

impl ResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.data;
            inputs.push(("data".to_string(), v.into_output()));
        }
        if let Some(v) = self.optional_data {
            inputs.push(("optionalData".to_string(), v.into_output()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Resource {
    resource: pulumi::Resource,
}

impl Resource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "optional-primitive-ref:index:Resource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "40.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Resource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn data(&self) -> pulumi::Output<crate::types::Data> {
        self.resource.output("data").cast()
    }

    pub fn optional_data(&self) -> pulumi::Output<Option<crate::types::Data>> {
        self.resource.output("optionalData").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:optional-primitive-ref".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "40.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

pub mod types {
    #[derive(Clone, Debug, Default)]
    pub struct DataArgs {
        pub boolean: Option<pulumi::Output<bool>>,
        pub boolean_map: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
        pub float: Option<pulumi::Output<f64>>,
        pub integer: Option<pulumi::Output<i32>>,
        pub number_array: Option<pulumi::Output<std::vec::Vec<f64>>>,
        pub string: Option<pulumi::Output<std::string::String>>,
    }

    impl DataArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.boolean {
                inputs.push(("boolean".to_string(), v.cast()));
            }
            if let Some(v) = self.boolean_map {
                inputs.push(("booleanMap".to_string(), v.cast()));
            }
            if let Some(v) = self.float {
                inputs.push(("float".to_string(), v.cast()));
            }
            if let Some(v) = self.integer {
                inputs.push(("integer".to_string(), v.cast()));
            }
            if let Some(v) = self.number_array {
                inputs.push(("numberArray".to_string(), v.cast()));
            }
            if let Some(v) = self.string {
                inputs.push(("string".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug)]
    pub struct Data {
        pub boolean: Option<bool>,
        pub boolean_map: Option<std::collections::BTreeMap<std::string::String, bool>>,
        pub float: Option<f64>,
        pub integer: Option<i32>,
        pub number_array: Option<std::vec::Vec<f64>>,
        pub string: Option<std::string::String>,
    }

    impl pulumi::FromPropertyValue for Data {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Data {
                boolean: pulumi::convert::from_property_map(&m, "boolean")?,
                boolean_map: pulumi::convert::from_property_map(&m, "booleanMap")?,
                float: pulumi::convert::from_property_map(&m, "float")?,
                integer: pulumi::convert::from_property_map(&m, "integer")?,
                number_array: pulumi::convert::from_property_map(&m, "numberArray")?,
                string: pulumi::convert::from_property_map(&m, "string")?,
            })
        }
    }
}
