// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:snake_names".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "33.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

pub mod cool_module {
    #[derive(Clone, Debug)]
    pub struct AnotherResourceArgs {
        pub the_input: pulumi::Output<std::string::String>,
    }

    impl AnotherResourceArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.the_input;
                inputs.push(("the_input".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone)]
    pub struct AnotherResource {
        resource: pulumi::Resource,
    }

    impl AnotherResource {
        pub fn new(ctx: &pulumi::Context, name: &str, args: AnotherResourceArgs, options: pulumi::ResourceOptions) -> AnotherResource {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "snake_names:cool_module:another_resource".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "33.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            AnotherResource { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<std::string::String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<std::string::String> {
            self.resource.id()
        }

        pub fn the_input(&self) -> pulumi::Output<std::string::String> {
            self.resource.output("the_input").cast()
        }
    }

    #[derive(Clone, Debug)]
    pub struct SomeResourceArgs {
        pub nested: crate::types::CoolModuleNestedInputArgs,
        pub the_input: pulumi::Output<bool>,
    }

    impl SomeResourceArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.nested;
                inputs.push(("nested".to_string(), v.into_output()));
            }
            {
                let v = self.the_input;
                inputs.push(("the_input".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone)]
    pub struct SomeResource {
        resource: pulumi::Resource,
    }

    impl SomeResource {
        pub fn new(ctx: &pulumi::Context, name: &str, args: SomeResourceArgs, options: pulumi::ResourceOptions) -> SomeResource {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "snake_names:cool_module:some_resource".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "33.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            SomeResource { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<std::string::String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<std::string::String> {
            self.resource.id()
        }

        pub fn the_output(&self) -> pulumi::Output<std::collections::BTreeMap<std::string::String, std::vec::Vec<crate::types::CoolModuleOutputItem>>> {
            self.resource.output("the_output").cast()
        }
    }

    #[derive(Clone, Debug)]
    pub struct SomeDataArgs {
        pub nested: std::vec::Vec<crate::types::CoolModuleEntryArgs>,
        pub the_input: pulumi::Output<std::string::String>,
    }

    impl SomeDataArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.nested;
                inputs.push(("nested".to_string(), pulumi::output::all(v.into_iter().map(|e| e.into_output()).collect()).cast()));
            }
            {
                let v = self.the_input;
                inputs.push(("the_input".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    pub fn some_data(ctx: &pulumi::Context, args: SomeDataArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::CoolModuleSomeDataResult> {
        let mut options = options;
        if options.version.is_empty() {
            options.version = "33.0.0".to_string();
        }
        ctx.invoke("snake_names:cool_module:some_data", args.into_inputs(), options).cast()
    }
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct CoolModuleEntryArgs {
        pub value: pulumi::Output<std::string::String>,
    }

    impl CoolModuleEntryArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.value;
                inputs.push(("value".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug)]
    pub struct CoolModuleNestedInputArgs {
        pub nested_value: pulumi::Output<std::string::String>,
    }

    impl CoolModuleNestedInputArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.nested_value;
                inputs.push(("nested_value".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug)]
    pub struct CoolModuleEntry {
        pub value: std::string::String,
    }

    impl pulumi::FromPropertyValue for CoolModuleEntry {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(CoolModuleEntry {
                value: pulumi::convert::from_property_map(&m, "value")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct CoolModuleOutputItem {
        pub nested_output: std::string::String,
    }

    impl pulumi::FromPropertyValue for CoolModuleOutputItem {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(CoolModuleOutputItem {
                nested_output: pulumi::convert::from_property_map(&m, "nested_output")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct CoolModuleSomeDataResult {
        pub nested_output: std::vec::Vec<std::collections::BTreeMap<std::string::String, crate::types::CoolModuleEntry>>,
    }

    impl pulumi::FromPropertyValue for CoolModuleSomeDataResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(CoolModuleSomeDataResult {
                nested_output: pulumi::convert::from_property_map(&m, "nested_output")?,
            })
        }
    }
}
