// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct SomeResourceArgs {
    pub builtins: pulumi::Output<std::string::String>,
    pub lambda: pulumi::Output<std::string::String>,
    pub property: pulumi::Output<std::string::String>,
}

impl SomeResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.builtins;
            inputs.push(("builtins".to_string(), v.cast()));
        }
        {
            let v = self.lambda;
            inputs.push(("lambda".to_string(), v.cast()));
        }
        {
            let v = self.property;
            inputs.push(("property".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct SomeResource {
    resource: pulumi::Resource,
}

impl SomeResource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: SomeResourceArgs, options: pulumi::ResourceOptions) -> SomeResource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "keywords:index:SomeResource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "20.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        SomeResource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn builtins(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("builtins").cast()
    }

    pub fn lambda(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("lambda").cast()
    }

    pub fn property(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("property").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:keywords".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "20.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

pub mod lambda {
    #[derive(Clone, Debug)]
    pub struct SomeResourceArgs {
        pub builtins: pulumi::Output<std::string::String>,
        pub lambda: pulumi::Output<std::string::String>,
        pub property: pulumi::Output<std::string::String>,
    }

    impl SomeResourceArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.builtins;
                inputs.push(("builtins".to_string(), v.cast()));
            }
            {
                let v = self.lambda;
                inputs.push(("lambda".to_string(), v.cast()));
            }
            {
                let v = self.property;
                inputs.push(("property".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone)]
    pub struct SomeResource {
        resource: pulumi::Resource,
    }

    impl SomeResource {
        pub fn new(ctx: &pulumi::Context, name: &str, args: SomeResourceArgs, options: pulumi::ResourceOptions) -> SomeResource {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "keywords:lambda:SomeResource".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "20.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            SomeResource { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<std::string::String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<std::string::String> {
            self.resource.id()
        }

        pub fn builtins(&self) -> pulumi::Output<std::string::String> {
            self.resource.output("builtins").cast()
        }

        pub fn lambda(&self) -> pulumi::Output<std::string::String> {
            self.resource.output("lambda").cast()
        }

        pub fn property(&self) -> pulumi::Output<std::string::String> {
            self.resource.output("property").cast()
        }
    }
}

pub mod module {
    #[derive(Clone, Debug)]
    pub struct LambdaArgs {
        pub builtins: pulumi::Output<std::string::String>,
        pub lambda: pulumi::Output<std::string::String>,
        pub property: pulumi::Output<std::string::String>,
    }

    impl LambdaArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.builtins;
                inputs.push(("builtins".to_string(), v.cast()));
            }
            {
                let v = self.lambda;
                inputs.push(("lambda".to_string(), v.cast()));
            }
            {
                let v = self.property;
                inputs.push(("property".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone)]
    pub struct Lambda {
        resource: pulumi::Resource,
    }

    impl Lambda {
        pub fn new(ctx: &pulumi::Context, name: &str, args: LambdaArgs, options: pulumi::ResourceOptions) -> Lambda {
            let resource = ctx.register_resource(pulumi::RegisterRequest {
                type_: "keywords:module:Lambda".to_string(),
                name: name.to_string(),
                custom: true,
                remote: false,
                version: "20.0.0".to_string(),
                plugin_download_url: "".to_string(),
                inputs: args.into_inputs(),
                options,
            });
            Lambda { resource }
        }

        pub fn pulumi_resource(&self) -> &pulumi::Resource {
            &self.resource
        }

        pub fn urn(&self) -> pulumi::Output<std::string::String> {
            self.resource.urn()
        }

        pub fn id(&self) -> pulumi::Output<std::string::String> {
            self.resource.id()
        }

        pub fn builtins(&self) -> pulumi::Output<std::string::String> {
            self.resource.output("builtins").cast()
        }

        pub fn lambda(&self) -> pulumi::Output<std::string::String> {
            self.resource.output("lambda").cast()
        }

        pub fn property(&self) -> pulumi::Output<std::string::String> {
            self.resource.output("property").cast()
        }
    }
}

