// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ContainerArgs {
    pub inputs: pulumi::Output<std::vec::Vec<std::string::String>>,
}

impl ContainerArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.inputs;
            inputs.push(("inputs".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Container {
    resource: pulumi::Resource,
}

impl Container {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ContainerArgs, options: pulumi::ResourceOptions) -> Container {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "nestedobject:index:Container".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "1.42.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Container { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn details(&self) -> pulumi::Output<std::vec::Vec<crate::types::Detail>> {
        self.resource.output("details").cast()
    }

    pub fn inputs(&self) -> pulumi::Output<std::vec::Vec<std::string::String>> {
        self.resource.output("inputs").cast()
    }
}

#[derive(Clone, Debug)]
pub struct MapContainerArgs {
    pub tags: pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>,
}

impl MapContainerArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.tags;
            inputs.push(("tags".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct MapContainer {
    resource: pulumi::Resource,
}

impl MapContainer {
    pub fn new(ctx: &pulumi::Context, name: &str, args: MapContainerArgs, options: pulumi::ResourceOptions) -> MapContainer {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "nestedobject:index:MapContainer".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "1.42.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        MapContainer { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn tags(&self) -> pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>> {
        self.resource.output("tags").cast()
    }
}

#[derive(Clone, Debug)]
pub struct ReceiverArgs {
    pub details: std::vec::Vec<crate::types::DetailArgs>,
}

impl ReceiverArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.details;
            inputs.push(("details".to_string(), pulumi::output::all(v.into_iter().map(|e| e.into_output()).collect()).cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Receiver {
    resource: pulumi::Resource,
}

impl Receiver {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ReceiverArgs, options: pulumi::ResourceOptions) -> Receiver {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "nestedobject:index:Receiver".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "1.42.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Receiver { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn details(&self) -> pulumi::Output<std::vec::Vec<crate::types::Detail>> {
        self.resource.output("details").cast()
    }
}

#[derive(Clone, Debug)]
pub struct TargetArgs {
    pub name: pulumi::Output<std::string::String>,
}

impl TargetArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.name;
            inputs.push(("name".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Target {
    resource: pulumi::Resource,
}

impl Target {
    pub fn new(ctx: &pulumi::Context, name: &str, args: TargetArgs, options: pulumi::ResourceOptions) -> Target {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "nestedobject:index:Target".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "1.42.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Target { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn name(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("name").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:nestedobject".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "1.42.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct GetValuesArgs {
    pub names: pulumi::Output<std::vec::Vec<std::string::String>>,
}

impl GetValuesArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.names;
            inputs.push(("names".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn get_values(ctx: &pulumi::Context, args: GetValuesArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::GetValuesResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "1.42.0".to_string();
    }
    ctx.invoke("nestedobject:index:getValues", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct DetailArgs {
        pub key: pulumi::Output<std::string::String>,
        pub value: pulumi::Output<std::string::String>,
    }

    impl DetailArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.key;
                inputs.push(("key".to_string(), v.cast()));
            }
            {
                let v = self.value;
                inputs.push(("value".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug)]
    pub struct Detail {
        pub key: std::string::String,
        pub value: std::string::String,
    }

    impl pulumi::FromPropertyValue for Detail {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Detail {
                key: pulumi::convert::from_property_map(&m, "key")?,
                value: pulumi::convert::from_property_map(&m, "value")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct GetValuesResult {
        pub results: std::vec::Vec<std::string::String>,
    }

    impl pulumi::FromPropertyValue for GetValuesResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(GetValuesResult {
                results: pulumi::convert::from_property_map(&m, "results")?,
            })
        }
    }
}
