// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        ctx.export("rootDirectoryOutput", pulumi::pv::string(std::env::var("PULUMI_ROOT_DIRECTORY").unwrap_or_default()));
        ctx.export("workingDirectoryOutput", pulumi::pv::cwd());
        Ok(())
    });
}
