// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let names = ctx.config().get_object_or("names", pulumi::PropertyValue::Array(vec![pulumi::PropertyValue::Null, pulumi::PropertyValue::String("hello".to_string()), pulumi::PropertyValue::Null]));
        ctx.export("namesLength", pulumi::pv::length(names.clone()));
        Ok(())
    });
}
