// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res1 = pulumi_simple::Resource::new(&ctx, "res1", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let local_var = res1.value().cast::<pulumi::PropertyValue>();
        let res2 = pulumi_simple::Resource::new(&ctx, "res2", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(local_var.clone()).cast() }, pulumi::ResourceOptions::default());
        ctx.export("out", res2.value().cast::<pulumi::PropertyValue>());
        Ok(())
    });
}
