// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        ctx.export("scalar", pulumi_simple_invoke_with_scalar_return::my_invoke_scalar(&ctx, pulumi_simple_invoke_with_scalar_return::MyInvokeScalarArgs { value: pulumi::pv::string("goodbye").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>());
        Ok(())
    });
}
