// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let res = pulumi_ref_ref::Resource::new(&ctx, "res", pulumi_ref_ref::ResourceArgs { data: pulumi_ref_ref::types::DataArgs { bool_array: pulumi::pv::array(vec![pulumi::ops::to_bool(pulumi::pv::bool(true))]).cast(), boolean: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast(), float: pulumi::ops::to_number(pulumi::pv::number(4.5)).cast(), inner_data: pulumi_ref_ref::types::InnerDataArgs { bool_array: pulumi::pv::array(vec![pulumi::ops::to_bool(pulumi::pv::bool(false)), pulumi::ops::to_bool(pulumi::pv::bool(true))]).cast(), boolean: pulumi::ops::to_bool(pulumi::pv::bool(false)).cast(), float: pulumi::ops::to_number(pulumi::pv::number(2.17)).cast(), integer: pulumi::ops::to_int(pulumi::pv::number(-12.0)).cast(), string: pulumi::ops::to_string(pulumi::pv::string("Goodbye")).cast(), string_map: pulumi::pv::object(vec![("two".to_string(), pulumi::ops::to_string(pulumi::pv::string("turtle doves"))), ("three".to_string(), pulumi::ops::to_string(pulumi::pv::string("french hens")))]).cast() }, inner_data_list: Some(vec![pulumi_ref_ref::types::InnerDataArgs { bool_array: pulumi::pv::array(vec![pulumi::ops::to_bool(pulumi::pv::bool(true))]).cast(), boolean: pulumi::ops::to_bool(pulumi::pv::bool(false)).cast(), float: pulumi::ops::to_number(pulumi::pv::number(3.14)).cast(), integer: pulumi::ops::to_int(pulumi::pv::number(42.0)).cast(), string: pulumi::ops::to_string(pulumi::pv::string("Partridge")).cast(), string_map: pulumi::pv::object(vec![("one".to_string(), pulumi::ops::to_string(pulumi::pv::string("in a pear tree")))]).cast() }]), integer: pulumi::ops::to_int(pulumi::pv::number(1024.0)).cast(), optional_inner: None, string: pulumi::ops::to_string(pulumi::pv::string("Hello")).cast(), string_map: pulumi::pv::object(vec![("x".to_string(), pulumi::ops::to_string(pulumi::pv::string("100"))), ("y".to_string(), pulumi::ops::to_string(pulumi::pv::string("200")))]).cast() } }, pulumi::ResourceOptions::default());
        ctx.export("bool", res.data().cast::<pulumi::PropertyValue>().index("boolean"));
        ctx.export("array", res.data().cast::<pulumi::PropertyValue>().index("boolArray").index(0usize));
        ctx.export("map", res.data().cast::<pulumi::PropertyValue>().index("stringMap").index("x"));
        ctx.export("nested", res.data().cast::<pulumi::PropertyValue>().index("innerData").index("stringMap").index("three"));
        ctx.export("listIndex", res.data().cast::<pulumi::PropertyValue>().index("innerDataList").index(0usize).index("string"));
        Ok(())
    });
}
