// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let my_component = pulumi_plaincomponent::Component::new(&ctx, "myComponent", pulumi_plaincomponent::ComponentArgs { name: "my-resource".to_string(), settings: pulumi_plaincomponent::types::SettingsArgs { enabled: true, tags: std::collections::BTreeMap::from([("env".to_string(), "test".to_string())]) } }, pulumi::ResourceOptions::default());
        ctx.export("label", my_component.label().cast::<pulumi::PropertyValue>());
        Ok(())
    });
}
