// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let with_option = pulumi_simple::Resource::new(&ctx, "withOption", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(false)).cast() }, pulumi::ResourceOptions { delete_before_replace: Some(true), replace_on_changes: vec!["value".to_string()], ..Default::default() });
        let without_option = pulumi_simple::Resource::new(&ctx, "withoutOption", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(false)).cast() }, pulumi::ResourceOptions { replace_on_changes: vec!["value".to_string()], ..Default::default() });
        Ok(())
    });
}
