// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ArchiveResourceArgs {
    pub value: pulumi::Output<pulumi::Archive>,
}

impl ArchiveResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ArchiveResource {
    resource: pulumi::Resource,
}

impl ArchiveResource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ArchiveResourceArgs, options: pulumi::ResourceOptions) -> ArchiveResource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "asset-archive:index:ArchiveResource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "5.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ArchiveResource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<pulumi::Archive> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug)]
pub struct AssetResourceArgs {
    pub value: pulumi::Output<pulumi::AssetOrArchive>,
}

impl AssetResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct AssetResource {
    resource: pulumi::Resource,
}

impl AssetResource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: AssetResourceArgs, options: pulumi::ResourceOptions) -> AssetResource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "asset-archive:index:AssetResource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "5.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        AssetResource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<pulumi::AssetOrArchive> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:asset-archive".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "5.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

