// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct StringResourceArgs {
    pub text: pulumi::Output<std::string::String>,
}

impl StringResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.text;
            inputs.push(("text".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct StringResource {
    resource: pulumi::Resource,
}

impl StringResource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: StringResourceArgs, options: pulumi::ResourceOptions) -> StringResource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "output-only-invoke:index:StringResource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "24.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        StringResource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn text(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("text").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:output-only-invoke".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "24.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct MyInvokeArgs {
    pub value: pulumi::Output<std::string::String>,
}

impl MyInvokeArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn my_invoke(ctx: &pulumi::Context, args: MyInvokeArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::MyInvokeResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "24.0.0".to_string();
    }
    ctx.invoke("output-only-invoke:index:myInvoke", args.into_inputs(), options).cast()
}

#[derive(Clone, Debug)]
pub struct SecretInvokeArgs {
    pub secret_response: pulumi::Output<bool>,
    pub value: pulumi::Output<std::string::String>,
}

impl SecretInvokeArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.secret_response;
            inputs.push(("secretResponse".to_string(), v.cast()));
        }
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn secret_invoke(ctx: &pulumi::Context, args: SecretInvokeArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::SecretInvokeResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "24.0.0".to_string();
    }
    ctx.invoke("output-only-invoke:index:secretInvoke", args.into_inputs(), options).cast()
}

#[derive(Clone, Debug, Default)]
pub struct UnitArgs {
}

impl UnitArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn unit(ctx: &pulumi::Context, args: UnitArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::UnitResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "24.0.0".to_string();
    }
    ctx.invoke("output-only-invoke:index:unit", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct MyInvokeResult {
        pub result: std::string::String,
    }

    impl pulumi::FromPropertyValue for MyInvokeResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(MyInvokeResult {
                result: pulumi::convert::from_property_map(&m, "result")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct SecretInvokeResult {
        pub response: std::string::String,
        pub secret: bool,
    }

    impl pulumi::FromPropertyValue for SecretInvokeResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(SecretInvokeResult {
                response: pulumi::convert::from_property_map(&m, "response")?,
                secret: pulumi::convert::from_property_map(&m, "secret")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct UnitResult {
        pub result: std::string::String,
    }

    impl pulumi::FromPropertyValue for UnitResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(UnitResult {
                result: pulumi::convert::from_property_map(&m, "result")?,
            })
        }
    }
}
