// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let class = pulumi::pv::string("class_output_string");
        let export = pulumi::pv::string("export_output_string");
        let import = pulumi::pv::string("import_output_string");
        let r#mod = pulumi::pv::string("mod_output_string");
        let object = pulumi::pv::object(vec![("object".to_string(), pulumi::pv::string("object_output_string"))]);
        let self_ = pulumi::pv::string("self_output_string");
        let this = pulumi::pv::string("this_output_string");
        let r#if = pulumi::pv::string("if_output_string");
        ctx.export("class", class.clone());
        ctx.export("export", export.clone());
        ctx.export("import", import.clone());
        ctx.export("mod", r#mod.clone());
        ctx.export("object", object.clone());
        ctx.export("self", self_.clone());
        ctx.export("this", this.clone());
        ctx.export("if", r#if.clone());
        Ok(())
    });
}
