[package]
name = "l2-resource-optional"
version = "0.1.0"
edition = "2021"

[dependencies]
pulumi = { path = "ROOT/artifacts/pulumi-0.1.0" }
pulumi_optionalprimitive = { path = "ROOT/artifacts/pulumi_optionalprimitive-34.0.0" }
pulumi_primitive = { path = "ROOT/artifacts/pulumi_primitive-7.0.0" }

[workspace]
