// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let a_map = ctx.config().require_object("aMap")?;
        ctx.export("entriesOutput", pulumi::pv::entries(a_map.clone()));
        ctx.export("lookupOutput", pulumi::pv::lookup(a_map.clone(), pulumi::pv::string("keyPresent"), pulumi::pv::string("default")));
        ctx.export("lookupOutputDefault", pulumi::pv::lookup(a_map.clone(), pulumi::pv::string("keyMissing"), pulumi::pv::string("default")));
        let alternative_names = ctx.config().get_object_or("alternativeNames", pulumi::PropertyValue::Object(std::collections::BTreeMap::from([])));
        ctx.export("names", pulumi::ops::for_array(pulumi::pv::entries(alternative_names.clone()), {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::bool(true) }, {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| __v0.clone().index("value") }));
        Ok(())
    });
}
