// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let a_number = pulumi::pv::secret(ctx.config().require_object("aNumber")?);
        ctx.export("roundtrip", a_number.clone());
        ctx.export("theSecretNumber", pulumi::ops::add(a_number.clone(), pulumi::pv::number(1.25)));
        Ok(())
    });
}
