// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let first = pulumi_simple_invoke::StringResource::new(&ctx, "first", pulumi_simple_invoke::StringResourceArgs { text: pulumi::ops::to_string(pulumi::pv::string("first hello")).cast() }, pulumi::ResourceOptions::default());
        let data = pulumi_simple_invoke::my_invoke(&ctx, pulumi_simple_invoke::MyInvokeArgs { value: pulumi::pv::string("hello").cast() }, pulumi::InvokeOptions { depends_on: vec![first.pulumi_resource().clone()], ..Default::default() }).cast::<pulumi::PropertyValue>();
        let second = pulumi_simple_invoke::StringResource::new(&ctx, "second", pulumi_simple_invoke::StringResourceArgs { text: pulumi::ops::to_string(data.clone().index("result")).cast() }, pulumi::ResourceOptions::default());
        ctx.export("hello", data.clone().index("result"));
        Ok(())
    });
}
