// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        ctx.export("empty", pulumi::pv::object(vec![]));
        ctx.export("strings", pulumi::pv::object(vec![("greeting".to_string(), pulumi::pv::string("Hello, world!")), ("farewell".to_string(), pulumi::pv::string("Goodbye, world!"))]));
        ctx.export("adversarialStrings", pulumi::pv::object(vec![("__type".to_string(), pulumi::pv::string("dunder type")), ("__internal".to_string(), pulumi::pv::string("dunder internal")), ("__provider".to_string(), pulumi::pv::string("dunder provider")), ("__version".to_string(), pulumi::pv::string("dunder version")), ("".to_string(), pulumi::pv::string("empty key")), ("empty value".to_string(), pulumi::pv::string("")), ("dunder value".to_string(), pulumi::pv::string("__dunder")), ("Some ${common} \"characters\" 'that' need escaping: \\ (backslash), \t (tab), \u{1b} (escape), \u{7} (bell), \u{0} (null), 󠀡 (tag space)".to_string(), pulumi::pv::string("Some ${common} \"characters\" 'that' need escaping: \\ (backslash), \t (tab), \u{1b} (escape), \u{7} (bell), \u{0} (null), 󠀡 (tag space)"))]));
        ctx.export("numbers", pulumi::pv::object(vec![("1".to_string(), pulumi::pv::number(1.0)), ("2".to_string(), pulumi::pv::number(2.0))]));
        ctx.export("keys", pulumi::pv::object(vec![("my.key".to_string(), pulumi::pv::number(1.0)), ("my-key".to_string(), pulumi::pv::number(2.0)), ("my_key".to_string(), pulumi::pv::number(3.0)), ("MY_KEY".to_string(), pulumi::pv::number(4.0)), ("mykey".to_string(), pulumi::pv::number(5.0)), ("MYKEY".to_string(), pulumi::pv::number(6.0))]));
        Ok(())
    });
}
