// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let a = ctx.config().require_number("a")?;
        let b = ctx.config().require_number("b")?;
        let c = ctx.config().require_int("c")?;
        let d = ctx.config().require_int("d")?;
        ctx.export("maxResult", pulumi::pv::max(vec![a.clone(), b.clone()]));
        ctx.export("minResult", pulumi::pv::min(vec![a.clone(), b.clone()]));
        ctx.export("intMaxResult", pulumi::pv::max(vec![c.clone(), d.clone()]));
        ctx.export("intMinResult", pulumi::pv::min(vec![c.clone(), d.clone()]));
        Ok(())
    });
}
