// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let sink1 = pulumi_enum::Res::new(&ctx, "sink1", pulumi_enum::ResArgs { int_enum: Some(pulumi::pv::number(1.0).cast()), string_enum: Some(pulumi::pv::string("two").cast()) }, pulumi::ResourceOptions::default());
        let sink2 = pulumi_enum::r#mod::Res::new(&ctx, "sink2", pulumi_enum::r#mod::ResArgs { int_enum: Some(pulumi::pv::number(1.0).cast()), string_enum: Some(pulumi::pv::string("two").cast()) }, pulumi::ResourceOptions::default());
        let sink3 = pulumi_enum::mod_nested::Res::new(&ctx, "sink3", pulumi_enum::mod_nested::ResArgs { int_enum: Some(pulumi::pv::number(1.0).cast()), string_enum: Some(pulumi::pv::string("two").cast()) }, pulumi::ResourceOptions::default());
        let sink4 = pulumi_enum::Deluxe::new(&ctx, "sink4", pulumi_enum::DeluxeArgs { array_of_enum: Some(pulumi::pv::array(vec![pulumi::pv::string("one"), pulumi::pv::string("two")]).cast()), holder: Some(pulumi_enum::types::HolderArgs { color: Some(pulumi::pv::string("one").cast()), size: Some(pulumi::pv::number(2.0).cast()) }), map_of_enum: Some(pulumi::pv::object(vec![("small".to_string(), pulumi::pv::number(1.0)), ("large".to_string(), pulumi::pv::number(2.0))]).cast()), number_enum: Some(pulumi::pv::number(0.1).cast()), union_enum: Some(pulumi::ops::to_string(pulumi::pv::string("A Value With Spaces.")).cast()), wordy_enum: Some(pulumi::pv::string("It's got apostrophes").cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
