// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let failing = pulumi_fail_on_create::Resource::new(&ctx, "failing", pulumi_fail_on_create::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(false)).cast() }, pulumi::ResourceOptions::default());
        let dependent = pulumi_simple::Resource::new(&ctx, "dependent", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { depends_on: vec![failing.pulumi_resource().clone()], ..Default::default() });
        let dependent_on_output = pulumi_simple::Resource::new(&ctx, "dependent_on_output", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(failing.value().cast::<pulumi::PropertyValue>()).cast() }, pulumi::ResourceOptions::default());
        let independent = pulumi_simple::Resource::new(&ctx, "independent", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let double_dependency = pulumi_simple::Resource::new(&ctx, "double_dependency", pulumi_simple::ResourceArgs { value: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions { depends_on: vec![independent.pulumi_resource().clone(), dependent_on_output.pulumi_resource().clone()], ..Default::default() });
        Ok(())
    });
}
