// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ComponentArgs {
    pub name: std::string::String,
    pub settings: crate::types::SettingsArgs,
}

impl ComponentArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.name;
            inputs.push(("name".to_string(), pulumi::Output::from_value(pulumi::IntoPropertyValue::into_property_value(v))));
        }
        {
            let v = self.settings;
            inputs.push(("settings".to_string(), v.into_output()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Component {
    resource: pulumi::Resource,
}

impl Component {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ComponentArgs, options: pulumi::ResourceOptions) -> Component {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "plaincomponent:index:Component".to_string(),
            name: name.to_string(),
            custom: false,
            remote: true,
            version: "36.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Component { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn label(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("label").cast()
    }
}

#[derive(Clone, Debug)]
pub struct CustomArgs {
    pub value: pulumi::Output<std::string::String>,
}

impl CustomArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Custom {
    resource: pulumi::Resource,
}

impl Custom {
    pub fn new(ctx: &pulumi::Context, name: &str, args: CustomArgs, options: pulumi::ResourceOptions) -> Custom {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "plaincomponent:index:Custom".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "36.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Custom { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn value(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("value").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:plaincomponent".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "36.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct SettingsArgs {
        pub enabled: bool,
        pub tags: std::collections::BTreeMap<std::string::String, std::string::String>,
    }

    impl SettingsArgs {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            {
                let v = self.enabled;
                inputs.push(("enabled".to_string(), pulumi::Output::from_value(pulumi::IntoPropertyValue::into_property_value(v))));
            }
            {
                let v = self.tags;
                inputs.push(("tags".to_string(), pulumi::Output::from_value(pulumi::IntoPropertyValue::into_property_value(v))));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }
}
