// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct StringResourceArgs {
    pub text: pulumi::Output<std::string::String>,
}

impl StringResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.text;
            inputs.push(("text".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct StringResource {
    resource: pulumi::Resource,
}

impl StringResource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: StringResourceArgs, options: pulumi::ResourceOptions) -> StringResource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "multi-argument-invoke:index:StringResource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "44.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        StringResource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn text(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("text").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:multi-argument-invoke".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "44.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct MultiArgumentInvokeArgs {
    pub first: pulumi::Output<std::string::String>,
    pub second: Option<pulumi::Output<std::string::String>>,
}

impl MultiArgumentInvokeArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.first;
            inputs.push(("first".to_string(), v.cast()));
        }
        if let Some(v) = self.second {
            inputs.push(("second".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn multi_argument_invoke(ctx: &pulumi::Context, args: MultiArgumentInvokeArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::MultiArgumentInvokeResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "44.0.0".to_string();
    }
    ctx.invoke("multi-argument-invoke:index:multiArgumentInvoke", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct MultiArgumentInvokeResult {
        pub result: std::string::String,
    }

    impl pulumi::FromPropertyValue for MultiArgumentInvokeResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(MultiArgumentInvokeResult {
                result: pulumi::convert::from_property_map(&m, "result")?,
            })
        }
    }
}
