// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let a_string = ctx.config().require_string("aString")?;
        let a_number = ctx.config().require_number("aNumber")?;
        let a_list = ctx.config().require_object("aList")?;
        let a_secret = pulumi::pv::secret(ctx.config().require_object("aSecret")?);
        ctx.export("stringOutput", pulumi::pv::to_json(a_string.clone()));
        ctx.export("numberOutput", pulumi::pv::to_json(a_number.clone()));
        ctx.export("boolOutput", pulumi::pv::to_json(pulumi::pv::bool(true)));
        ctx.export("arrayOutput", pulumi::pv::to_json(pulumi::pv::array(vec![pulumi::pv::string("x"), pulumi::pv::string("y"), pulumi::pv::string("z")])));
        ctx.export("objectOutput", pulumi::pv::to_json(pulumi::pv::object(vec![("key".to_string(), pulumi::pv::string("value")), ("count".to_string(), pulumi::pv::number(1.0))])));
        let nested_object = pulumi::pv::object(vec![("anObject".to_string(), pulumi::pv::object(vec![("name".to_string(), a_string.clone()), ("items".to_string(), a_list.clone())])), ("a_secret".to_string(), a_secret.clone())]);
        ctx.export("nestedOutput", pulumi::pv::to_json(nested_object.clone()));
        Ok(())
    });
}
