// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let names = ctx.config().require_object("names")?;
        let tags = ctx.config().require_object("tags")?;
        ctx.export("greetings", pulumi::ops::for_array(names.clone(), {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::bool(true) }, {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::concat(vec![pulumi::pv::string("Hello, "), __v0.clone(), pulumi::pv::string("!")]) }));
        ctx.export("numbered", pulumi::ops::for_array(names.clone(), {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::bool(true) }, {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::concat(vec![__k0.clone(), pulumi::pv::string("-"), __v0.clone()]) }));
        ctx.export("tagList", pulumi::ops::for_array(tags.clone(), {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::bool(true) }, {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::concat(vec![__k0.clone(), pulumi::pv::string("="), __v0.clone()]) }));
        ctx.export("greetingMap", pulumi::ops::for_object(names.clone(), {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::bool(true) }, {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| __v0.clone() }, {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::concat(vec![pulumi::pv::string("Hello, "), __v0.clone(), pulumi::pv::string("!")]) }));
        ctx.export("filteredList", pulumi::ops::for_array(names.clone(), {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::ops::neq(__v0.clone(), pulumi::pv::string("b")) }, {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| __v0.clone() }));
        ctx.export("filteredMap", pulumi::ops::for_object(names.clone(), {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::ops::neq(__v0.clone(), pulumi::pv::string("b")) }, {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| __v0.clone() }, {  move |__k0: pulumi::Output<pulumi::PropertyValue>, __v0: pulumi::Output<pulumi::PropertyValue>| pulumi::pv::concat(vec![pulumi::pv::string("Hello, "), __v0.clone(), pulumi::pv::string("!")]) }));
        Ok(())
    });
}
