// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let enum_res = pulumi_enum::Res::new(&ctx, "enumRes", pulumi_enum::ResArgs { int_enum: Some(pulumi::pv::number(1.0).cast()), string_enum: Some(pulumi::pv::string("one").cast()) }, pulumi::ResourceOptions::default());
        let res = pulumi_docs::Resource::new(&ctx, "res", pulumi_docs::ResourceArgs { external_enum: pulumi::pv::string("one").cast(), r#in: pulumi::ops::to_bool(pulumi_docs::fun(&ctx, pulumi_docs::FunArgs { r#in: pulumi::pv::bool(false).cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("out")).cast() }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
