// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ConfigFetcherArgs {
}

impl ConfigFetcherArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct ConfigFetcher {
    resource: pulumi::Resource,
}

impl ConfigFetcher {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ConfigFetcherArgs, options: pulumi::ResourceOptions) -> ConfigFetcher {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "config-grpc:index:ConfigFetcher".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "1.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        ConfigFetcher { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn config(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("config").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
    pub bool1: Option<pulumi::Output<bool>>,
    pub bool2: Option<pulumi::Output<bool>>,
    pub bool3: Option<pulumi::Output<bool>>,
    pub int1: Option<pulumi::Output<i32>>,
    pub int2: Option<pulumi::Output<i32>>,
    pub int3: Option<pulumi::Output<i32>>,
    pub list_bool1: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_bool2: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_bool3: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_int1: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_int2: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_int3: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_num1: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_num2: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_num3: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_secret_bool1: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_secret_bool2: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_secret_bool3: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_secret_int1: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_secret_int2: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_secret_int3: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_secret_num1: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_secret_num2: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_secret_num3: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_secret_string1: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub list_secret_string2: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub list_secret_string3: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub list_string1: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub list_string2: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub list_string3: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub map_bool1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_bool2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_bool3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_int1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_int2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_int3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_num1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_num2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_num3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_secret_bool1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_secret_bool2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_secret_bool3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_secret_int1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_secret_int2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_secret_int3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_secret_num1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_secret_num2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_secret_num3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_secret_string1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub map_secret_string2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub map_secret_string3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub map_string1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub map_string2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub map_string3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub num1: Option<pulumi::Output<f64>>,
    pub num2: Option<pulumi::Output<f64>>,
    pub num3: Option<pulumi::Output<f64>>,
    pub obj_bool1: Option<crate::types::Tbool1Args>,
    pub obj_bool2: Option<crate::types::Tbool2Args>,
    pub obj_bool3: Option<crate::types::Tbool3Args>,
    pub obj_int1: Option<crate::types::Tint1Args>,
    pub obj_int2: Option<crate::types::Tint2Args>,
    pub obj_int3: Option<crate::types::Tint3Args>,
    pub obj_num1: Option<crate::types::Tnum1Args>,
    pub obj_num2: Option<crate::types::Tnum2Args>,
    pub obj_num3: Option<crate::types::Tnum3Args>,
    pub obj_secret_bool1: Option<crate::types::TsecretBool1Args>,
    pub obj_secret_bool2: Option<crate::types::TsecretBool2Args>,
    pub obj_secret_bool3: Option<crate::types::TsecretBool3Args>,
    pub obj_secret_int1: Option<crate::types::TsecretInt1Args>,
    pub obj_secret_int2: Option<crate::types::TsecretInt2Args>,
    pub obj_secret_int3: Option<crate::types::TsecretInt3Args>,
    pub obj_secret_num1: Option<crate::types::TsecretNum1Args>,
    pub obj_secret_num2: Option<crate::types::TsecretNum2Args>,
    pub obj_secret_num3: Option<crate::types::TsecretNum3Args>,
    pub obj_secret_string1: Option<crate::types::TsecretString1Args>,
    pub obj_secret_string2: Option<crate::types::TsecretString2Args>,
    pub obj_secret_string3: Option<crate::types::TsecretString3Args>,
    pub obj_string1: Option<crate::types::Tstring1Args>,
    pub obj_string2: Option<crate::types::Tstring2Args>,
    pub obj_string3: Option<crate::types::Tstring3Args>,
    pub secret_bool1: Option<pulumi::Output<bool>>,
    pub secret_bool2: Option<pulumi::Output<bool>>,
    pub secret_bool3: Option<pulumi::Output<bool>>,
    pub secret_int1: Option<pulumi::Output<i32>>,
    pub secret_int2: Option<pulumi::Output<i32>>,
    pub secret_int3: Option<pulumi::Output<i32>>,
    pub secret_num1: Option<pulumi::Output<f64>>,
    pub secret_num2: Option<pulumi::Output<f64>>,
    pub secret_num3: Option<pulumi::Output<f64>>,
    pub secret_string1: Option<pulumi::Output<std::string::String>>,
    pub secret_string2: Option<pulumi::Output<std::string::String>>,
    pub secret_string3: Option<pulumi::Output<std::string::String>>,
    pub string1: Option<pulumi::Output<std::string::String>>,
    pub string2: Option<pulumi::Output<std::string::String>>,
    pub string3: Option<pulumi::Output<std::string::String>>,
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.bool1 {
            inputs.push(("bool1".to_string(), v.cast()));
        }
        if let Some(v) = self.bool2 {
            inputs.push(("bool2".to_string(), v.cast()));
        }
        if let Some(v) = self.bool3 {
            inputs.push(("bool3".to_string(), v.cast()));
        }
        if let Some(v) = self.int1 {
            inputs.push(("int1".to_string(), v.cast()));
        }
        if let Some(v) = self.int2 {
            inputs.push(("int2".to_string(), v.cast()));
        }
        if let Some(v) = self.int3 {
            inputs.push(("int3".to_string(), v.cast()));
        }
        if let Some(v) = self.list_bool1 {
            inputs.push(("listBool1".to_string(), v.cast()));
        }
        if let Some(v) = self.list_bool2 {
            inputs.push(("listBool2".to_string(), v.cast()));
        }
        if let Some(v) = self.list_bool3 {
            inputs.push(("listBool3".to_string(), v.cast()));
        }
        if let Some(v) = self.list_int1 {
            inputs.push(("listInt1".to_string(), v.cast()));
        }
        if let Some(v) = self.list_int2 {
            inputs.push(("listInt2".to_string(), v.cast()));
        }
        if let Some(v) = self.list_int3 {
            inputs.push(("listInt3".to_string(), v.cast()));
        }
        if let Some(v) = self.list_num1 {
            inputs.push(("listNum1".to_string(), v.cast()));
        }
        if let Some(v) = self.list_num2 {
            inputs.push(("listNum2".to_string(), v.cast()));
        }
        if let Some(v) = self.list_num3 {
            inputs.push(("listNum3".to_string(), v.cast()));
        }
        if let Some(v) = self.list_secret_bool1 {
            inputs.push(("listSecretBool1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_bool2 {
            inputs.push(("listSecretBool2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_bool3 {
            inputs.push(("listSecretBool3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_int1 {
            inputs.push(("listSecretInt1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_int2 {
            inputs.push(("listSecretInt2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_int3 {
            inputs.push(("listSecretInt3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_num1 {
            inputs.push(("listSecretNum1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_num2 {
            inputs.push(("listSecretNum2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_num3 {
            inputs.push(("listSecretNum3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_string1 {
            inputs.push(("listSecretString1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_string2 {
            inputs.push(("listSecretString2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_string3 {
            inputs.push(("listSecretString3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_string1 {
            inputs.push(("listString1".to_string(), v.cast()));
        }
        if let Some(v) = self.list_string2 {
            inputs.push(("listString2".to_string(), v.cast()));
        }
        if let Some(v) = self.list_string3 {
            inputs.push(("listString3".to_string(), v.cast()));
        }
        if let Some(v) = self.map_bool1 {
            inputs.push(("mapBool1".to_string(), v.cast()));
        }
        if let Some(v) = self.map_bool2 {
            inputs.push(("mapBool2".to_string(), v.cast()));
        }
        if let Some(v) = self.map_bool3 {
            inputs.push(("mapBool3".to_string(), v.cast()));
        }
        if let Some(v) = self.map_int1 {
            inputs.push(("mapInt1".to_string(), v.cast()));
        }
        if let Some(v) = self.map_int2 {
            inputs.push(("mapInt2".to_string(), v.cast()));
        }
        if let Some(v) = self.map_int3 {
            inputs.push(("mapInt3".to_string(), v.cast()));
        }
        if let Some(v) = self.map_num1 {
            inputs.push(("mapNum1".to_string(), v.cast()));
        }
        if let Some(v) = self.map_num2 {
            inputs.push(("mapNum2".to_string(), v.cast()));
        }
        if let Some(v) = self.map_num3 {
            inputs.push(("mapNum3".to_string(), v.cast()));
        }
        if let Some(v) = self.map_secret_bool1 {
            inputs.push(("mapSecretBool1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_bool2 {
            inputs.push(("mapSecretBool2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_bool3 {
            inputs.push(("mapSecretBool3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_int1 {
            inputs.push(("mapSecretInt1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_int2 {
            inputs.push(("mapSecretInt2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_int3 {
            inputs.push(("mapSecretInt3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_num1 {
            inputs.push(("mapSecretNum1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_num2 {
            inputs.push(("mapSecretNum2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_num3 {
            inputs.push(("mapSecretNum3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_string1 {
            inputs.push(("mapSecretString1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_string2 {
            inputs.push(("mapSecretString2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_string3 {
            inputs.push(("mapSecretString3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_string1 {
            inputs.push(("mapString1".to_string(), v.cast()));
        }
        if let Some(v) = self.map_string2 {
            inputs.push(("mapString2".to_string(), v.cast()));
        }
        if let Some(v) = self.map_string3 {
            inputs.push(("mapString3".to_string(), v.cast()));
        }
        if let Some(v) = self.num1 {
            inputs.push(("num1".to_string(), v.cast()));
        }
        if let Some(v) = self.num2 {
            inputs.push(("num2".to_string(), v.cast()));
        }
        if let Some(v) = self.num3 {
            inputs.push(("num3".to_string(), v.cast()));
        }
        if let Some(v) = self.obj_bool1 {
            inputs.push(("objBool1".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_bool2 {
            inputs.push(("objBool2".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_bool3 {
            inputs.push(("objBool3".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_int1 {
            inputs.push(("objInt1".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_int2 {
            inputs.push(("objInt2".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_int3 {
            inputs.push(("objInt3".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_num1 {
            inputs.push(("objNum1".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_num2 {
            inputs.push(("objNum2".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_num3 {
            inputs.push(("objNum3".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_secret_bool1 {
            inputs.push(("objSecretBool1".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_bool2 {
            inputs.push(("objSecretBool2".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_bool3 {
            inputs.push(("objSecretBool3".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_int1 {
            inputs.push(("objSecretInt1".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_int2 {
            inputs.push(("objSecretInt2".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_int3 {
            inputs.push(("objSecretInt3".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_num1 {
            inputs.push(("objSecretNum1".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_num2 {
            inputs.push(("objSecretNum2".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_num3 {
            inputs.push(("objSecretNum3".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_string1 {
            inputs.push(("objSecretString1".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_string2 {
            inputs.push(("objSecretString2".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_string3 {
            inputs.push(("objSecretString3".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_string1 {
            inputs.push(("objString1".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_string2 {
            inputs.push(("objString2".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_string3 {
            inputs.push(("objString3".to_string(), v.into_output()));
        }
        if let Some(v) = self.secret_bool1 {
            inputs.push(("secretBool1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_bool2 {
            inputs.push(("secretBool2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_bool3 {
            inputs.push(("secretBool3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_int1 {
            inputs.push(("secretInt1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_int2 {
            inputs.push(("secretInt2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_int3 {
            inputs.push(("secretInt3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_num1 {
            inputs.push(("secretNum1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_num2 {
            inputs.push(("secretNum2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_num3 {
            inputs.push(("secretNum3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_string1 {
            inputs.push(("secretString1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_string2 {
            inputs.push(("secretString2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_string3 {
            inputs.push(("secretString3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.string1 {
            inputs.push(("string1".to_string(), v.cast()));
        }
        if let Some(v) = self.string2 {
            inputs.push(("string2".to_string(), v.cast()));
        }
        if let Some(v) = self.string3 {
            inputs.push(("string3".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let mut options = options;
        options.additional_secret_outputs.push("secretString1".to_string());
        options.additional_secret_outputs.push("secretString2".to_string());
        options.additional_secret_outputs.push("secretString3".to_string());
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:config-grpc".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "1.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn secret_string1(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("secretString1").as_secret().cast()
    }

    pub fn secret_string2(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("secretString2").as_secret().cast()
    }

    pub fn secret_string3(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("secretString3").as_secret().cast()
    }

    pub fn string1(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("string1").cast()
    }

    pub fn string2(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("string2").cast()
    }

    pub fn string3(&self) -> pulumi::Output<Option<std::string::String>> {
        self.resource.output("string3").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ToSecretArgs {
    pub bool1: Option<pulumi::Output<bool>>,
    pub bool2: Option<pulumi::Output<bool>>,
    pub bool3: Option<pulumi::Output<bool>>,
    pub int1: Option<pulumi::Output<i32>>,
    pub int2: Option<pulumi::Output<i32>>,
    pub int3: Option<pulumi::Output<i32>>,
    pub list_bool1: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_bool2: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_bool3: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_int1: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_int2: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_int3: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_num1: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_num2: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_num3: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_secret_bool1: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_secret_bool2: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_secret_bool3: Option<pulumi::Output<std::vec::Vec<bool>>>,
    pub list_secret_int1: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_secret_int2: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_secret_int3: Option<pulumi::Output<std::vec::Vec<i32>>>,
    pub list_secret_num1: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_secret_num2: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_secret_num3: Option<pulumi::Output<std::vec::Vec<f64>>>,
    pub list_secret_string1: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub list_secret_string2: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub list_secret_string3: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub list_string1: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub list_string2: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub list_string3: Option<pulumi::Output<std::vec::Vec<std::string::String>>>,
    pub map_bool1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_bool2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_bool3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_int1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_int2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_int3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_num1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_num2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_num3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_secret_bool1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_secret_bool2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_secret_bool3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>>,
    pub map_secret_int1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_secret_int2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_secret_int3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, i32>>>,
    pub map_secret_num1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_secret_num2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_secret_num3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, f64>>>,
    pub map_secret_string1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub map_secret_string2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub map_secret_string3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub map_string1: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub map_string2: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub map_string3: Option<pulumi::Output<std::collections::BTreeMap<std::string::String, std::string::String>>>,
    pub num1: Option<pulumi::Output<f64>>,
    pub num2: Option<pulumi::Output<f64>>,
    pub num3: Option<pulumi::Output<f64>>,
    pub obj_bool1: Option<crate::types::Tbool1Args>,
    pub obj_bool2: Option<crate::types::Tbool2Args>,
    pub obj_bool3: Option<crate::types::Tbool3Args>,
    pub obj_int1: Option<crate::types::Tint1Args>,
    pub obj_int2: Option<crate::types::Tint2Args>,
    pub obj_int3: Option<crate::types::Tint3Args>,
    pub obj_num1: Option<crate::types::Tnum1Args>,
    pub obj_num2: Option<crate::types::Tnum2Args>,
    pub obj_num3: Option<crate::types::Tnum3Args>,
    pub obj_secret_bool1: Option<crate::types::TsecretBool1Args>,
    pub obj_secret_bool2: Option<crate::types::TsecretBool2Args>,
    pub obj_secret_bool3: Option<crate::types::TsecretBool3Args>,
    pub obj_secret_int1: Option<crate::types::TsecretInt1Args>,
    pub obj_secret_int2: Option<crate::types::TsecretInt2Args>,
    pub obj_secret_int3: Option<crate::types::TsecretInt3Args>,
    pub obj_secret_num1: Option<crate::types::TsecretNum1Args>,
    pub obj_secret_num2: Option<crate::types::TsecretNum2Args>,
    pub obj_secret_num3: Option<crate::types::TsecretNum3Args>,
    pub obj_secret_string1: Option<crate::types::TsecretString1Args>,
    pub obj_secret_string2: Option<crate::types::TsecretString2Args>,
    pub obj_secret_string3: Option<crate::types::TsecretString3Args>,
    pub obj_string1: Option<crate::types::Tstring1Args>,
    pub obj_string2: Option<crate::types::Tstring2Args>,
    pub obj_string3: Option<crate::types::Tstring3Args>,
    pub secret_bool1: Option<pulumi::Output<bool>>,
    pub secret_bool2: Option<pulumi::Output<bool>>,
    pub secret_bool3: Option<pulumi::Output<bool>>,
    pub secret_int1: Option<pulumi::Output<i32>>,
    pub secret_int2: Option<pulumi::Output<i32>>,
    pub secret_int3: Option<pulumi::Output<i32>>,
    pub secret_num1: Option<pulumi::Output<f64>>,
    pub secret_num2: Option<pulumi::Output<f64>>,
    pub secret_num3: Option<pulumi::Output<f64>>,
    pub secret_string1: Option<pulumi::Output<std::string::String>>,
    pub secret_string2: Option<pulumi::Output<std::string::String>>,
    pub secret_string3: Option<pulumi::Output<std::string::String>>,
    pub string1: Option<pulumi::Output<std::string::String>>,
    pub string2: Option<pulumi::Output<std::string::String>>,
    pub string3: Option<pulumi::Output<std::string::String>>,
}

impl ToSecretArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        if let Some(v) = self.bool1 {
            inputs.push(("bool1".to_string(), v.cast()));
        }
        if let Some(v) = self.bool2 {
            inputs.push(("bool2".to_string(), v.cast()));
        }
        if let Some(v) = self.bool3 {
            inputs.push(("bool3".to_string(), v.cast()));
        }
        if let Some(v) = self.int1 {
            inputs.push(("int1".to_string(), v.cast()));
        }
        if let Some(v) = self.int2 {
            inputs.push(("int2".to_string(), v.cast()));
        }
        if let Some(v) = self.int3 {
            inputs.push(("int3".to_string(), v.cast()));
        }
        if let Some(v) = self.list_bool1 {
            inputs.push(("listBool1".to_string(), v.cast()));
        }
        if let Some(v) = self.list_bool2 {
            inputs.push(("listBool2".to_string(), v.cast()));
        }
        if let Some(v) = self.list_bool3 {
            inputs.push(("listBool3".to_string(), v.cast()));
        }
        if let Some(v) = self.list_int1 {
            inputs.push(("listInt1".to_string(), v.cast()));
        }
        if let Some(v) = self.list_int2 {
            inputs.push(("listInt2".to_string(), v.cast()));
        }
        if let Some(v) = self.list_int3 {
            inputs.push(("listInt3".to_string(), v.cast()));
        }
        if let Some(v) = self.list_num1 {
            inputs.push(("listNum1".to_string(), v.cast()));
        }
        if let Some(v) = self.list_num2 {
            inputs.push(("listNum2".to_string(), v.cast()));
        }
        if let Some(v) = self.list_num3 {
            inputs.push(("listNum3".to_string(), v.cast()));
        }
        if let Some(v) = self.list_secret_bool1 {
            inputs.push(("listSecretBool1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_bool2 {
            inputs.push(("listSecretBool2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_bool3 {
            inputs.push(("listSecretBool3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_int1 {
            inputs.push(("listSecretInt1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_int2 {
            inputs.push(("listSecretInt2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_int3 {
            inputs.push(("listSecretInt3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_num1 {
            inputs.push(("listSecretNum1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_num2 {
            inputs.push(("listSecretNum2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_num3 {
            inputs.push(("listSecretNum3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_string1 {
            inputs.push(("listSecretString1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_string2 {
            inputs.push(("listSecretString2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_secret_string3 {
            inputs.push(("listSecretString3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.list_string1 {
            inputs.push(("listString1".to_string(), v.cast()));
        }
        if let Some(v) = self.list_string2 {
            inputs.push(("listString2".to_string(), v.cast()));
        }
        if let Some(v) = self.list_string3 {
            inputs.push(("listString3".to_string(), v.cast()));
        }
        if let Some(v) = self.map_bool1 {
            inputs.push(("mapBool1".to_string(), v.cast()));
        }
        if let Some(v) = self.map_bool2 {
            inputs.push(("mapBool2".to_string(), v.cast()));
        }
        if let Some(v) = self.map_bool3 {
            inputs.push(("mapBool3".to_string(), v.cast()));
        }
        if let Some(v) = self.map_int1 {
            inputs.push(("mapInt1".to_string(), v.cast()));
        }
        if let Some(v) = self.map_int2 {
            inputs.push(("mapInt2".to_string(), v.cast()));
        }
        if let Some(v) = self.map_int3 {
            inputs.push(("mapInt3".to_string(), v.cast()));
        }
        if let Some(v) = self.map_num1 {
            inputs.push(("mapNum1".to_string(), v.cast()));
        }
        if let Some(v) = self.map_num2 {
            inputs.push(("mapNum2".to_string(), v.cast()));
        }
        if let Some(v) = self.map_num3 {
            inputs.push(("mapNum3".to_string(), v.cast()));
        }
        if let Some(v) = self.map_secret_bool1 {
            inputs.push(("mapSecretBool1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_bool2 {
            inputs.push(("mapSecretBool2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_bool3 {
            inputs.push(("mapSecretBool3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_int1 {
            inputs.push(("mapSecretInt1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_int2 {
            inputs.push(("mapSecretInt2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_int3 {
            inputs.push(("mapSecretInt3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_num1 {
            inputs.push(("mapSecretNum1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_num2 {
            inputs.push(("mapSecretNum2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_num3 {
            inputs.push(("mapSecretNum3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_string1 {
            inputs.push(("mapSecretString1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_string2 {
            inputs.push(("mapSecretString2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_secret_string3 {
            inputs.push(("mapSecretString3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.map_string1 {
            inputs.push(("mapString1".to_string(), v.cast()));
        }
        if let Some(v) = self.map_string2 {
            inputs.push(("mapString2".to_string(), v.cast()));
        }
        if let Some(v) = self.map_string3 {
            inputs.push(("mapString3".to_string(), v.cast()));
        }
        if let Some(v) = self.num1 {
            inputs.push(("num1".to_string(), v.cast()));
        }
        if let Some(v) = self.num2 {
            inputs.push(("num2".to_string(), v.cast()));
        }
        if let Some(v) = self.num3 {
            inputs.push(("num3".to_string(), v.cast()));
        }
        if let Some(v) = self.obj_bool1 {
            inputs.push(("objBool1".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_bool2 {
            inputs.push(("objBool2".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_bool3 {
            inputs.push(("objBool3".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_int1 {
            inputs.push(("objInt1".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_int2 {
            inputs.push(("objInt2".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_int3 {
            inputs.push(("objInt3".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_num1 {
            inputs.push(("objNum1".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_num2 {
            inputs.push(("objNum2".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_num3 {
            inputs.push(("objNum3".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_secret_bool1 {
            inputs.push(("objSecretBool1".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_bool2 {
            inputs.push(("objSecretBool2".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_bool3 {
            inputs.push(("objSecretBool3".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_int1 {
            inputs.push(("objSecretInt1".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_int2 {
            inputs.push(("objSecretInt2".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_int3 {
            inputs.push(("objSecretInt3".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_num1 {
            inputs.push(("objSecretNum1".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_num2 {
            inputs.push(("objSecretNum2".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_num3 {
            inputs.push(("objSecretNum3".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_string1 {
            inputs.push(("objSecretString1".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_string2 {
            inputs.push(("objSecretString2".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_secret_string3 {
            inputs.push(("objSecretString3".to_string(), pulumi::pv::secret(v.into_output())));
        }
        if let Some(v) = self.obj_string1 {
            inputs.push(("objString1".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_string2 {
            inputs.push(("objString2".to_string(), v.into_output()));
        }
        if let Some(v) = self.obj_string3 {
            inputs.push(("objString3".to_string(), v.into_output()));
        }
        if let Some(v) = self.secret_bool1 {
            inputs.push(("secretBool1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_bool2 {
            inputs.push(("secretBool2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_bool3 {
            inputs.push(("secretBool3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_int1 {
            inputs.push(("secretInt1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_int2 {
            inputs.push(("secretInt2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_int3 {
            inputs.push(("secretInt3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_num1 {
            inputs.push(("secretNum1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_num2 {
            inputs.push(("secretNum2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_num3 {
            inputs.push(("secretNum3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_string1 {
            inputs.push(("secretString1".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_string2 {
            inputs.push(("secretString2".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.secret_string3 {
            inputs.push(("secretString3".to_string(), pulumi::pv::secret(v.cast())));
        }
        if let Some(v) = self.string1 {
            inputs.push(("string1".to_string(), v.cast()));
        }
        if let Some(v) = self.string2 {
            inputs.push(("string2".to_string(), v.cast()));
        }
        if let Some(v) = self.string3 {
            inputs.push(("string3".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn to_secret(ctx: &pulumi::Context, args: ToSecretArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::ToSecretResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "1.0.0".to_string();
    }
    ctx.invoke("config-grpc:index:toSecret", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug, Default)]
    pub struct Tbool1Args {
        pub x: Option<pulumi::Output<bool>>,
    }

    impl Tbool1Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tbool2Args {
        pub x: Option<pulumi::Output<bool>>,
    }

    impl Tbool2Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tbool3Args {
        pub x: Option<pulumi::Output<bool>>,
    }

    impl Tbool3Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tint1Args {
        pub x: Option<pulumi::Output<i32>>,
    }

    impl Tint1Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tint2Args {
        pub x: Option<pulumi::Output<i32>>,
    }

    impl Tint2Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tint3Args {
        pub x: Option<pulumi::Output<i32>>,
    }

    impl Tint3Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tnum1Args {
        pub x: Option<pulumi::Output<f64>>,
    }

    impl Tnum1Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tnum2Args {
        pub x: Option<pulumi::Output<f64>>,
    }

    impl Tnum2Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tnum3Args {
        pub x: Option<pulumi::Output<f64>>,
    }

    impl Tnum3Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretBool1Args {
        pub secret_x: Option<pulumi::Output<bool>>,
    }

    impl TsecretBool1Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretBool2Args {
        pub secret_x: Option<pulumi::Output<bool>>,
    }

    impl TsecretBool2Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretBool3Args {
        pub secret_x: Option<pulumi::Output<bool>>,
    }

    impl TsecretBool3Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretInt1Args {
        pub secret_x: Option<pulumi::Output<i32>>,
    }

    impl TsecretInt1Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretInt2Args {
        pub secret_x: Option<pulumi::Output<i32>>,
    }

    impl TsecretInt2Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretInt3Args {
        pub secret_x: Option<pulumi::Output<i32>>,
    }

    impl TsecretInt3Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretNum1Args {
        pub secret_x: Option<pulumi::Output<f64>>,
    }

    impl TsecretNum1Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretNum2Args {
        pub secret_x: Option<pulumi::Output<f64>>,
    }

    impl TsecretNum2Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretNum3Args {
        pub secret_x: Option<pulumi::Output<f64>>,
    }

    impl TsecretNum3Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretString1Args {
        pub secret_x: Option<pulumi::Output<std::string::String>>,
    }

    impl TsecretString1Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretString2Args {
        pub secret_x: Option<pulumi::Output<std::string::String>>,
    }

    impl TsecretString2Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct TsecretString3Args {
        pub secret_x: Option<pulumi::Output<std::string::String>>,
    }

    impl TsecretString3Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.secret_x {
                inputs.push(("secretX".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tstring1Args {
        pub x: Option<pulumi::Output<std::string::String>>,
    }

    impl Tstring1Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tstring2Args {
        pub x: Option<pulumi::Output<std::string::String>>,
    }

    impl Tstring2Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug, Default)]
    pub struct Tstring3Args {
        pub x: Option<pulumi::Output<std::string::String>>,
    }

    impl Tstring3Args {
        pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
            let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
            if let Some(v) = self.x {
                inputs.push(("x".to_string(), v.cast()));
            }
            inputs
        }

        pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
            pulumi::output::object(self.into_inputs())
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tbool1 {
        pub x: Option<bool>,
    }

    impl pulumi::FromPropertyValue for Tbool1 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tbool1 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tbool2 {
        pub x: Option<bool>,
    }

    impl pulumi::FromPropertyValue for Tbool2 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tbool2 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tbool3 {
        pub x: Option<bool>,
    }

    impl pulumi::FromPropertyValue for Tbool3 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tbool3 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tint1 {
        pub x: Option<i32>,
    }

    impl pulumi::FromPropertyValue for Tint1 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tint1 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tint2 {
        pub x: Option<i32>,
    }

    impl pulumi::FromPropertyValue for Tint2 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tint2 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tint3 {
        pub x: Option<i32>,
    }

    impl pulumi::FromPropertyValue for Tint3 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tint3 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tnum1 {
        pub x: Option<f64>,
    }

    impl pulumi::FromPropertyValue for Tnum1 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tnum1 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tnum2 {
        pub x: Option<f64>,
    }

    impl pulumi::FromPropertyValue for Tnum2 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tnum2 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tnum3 {
        pub x: Option<f64>,
    }

    impl pulumi::FromPropertyValue for Tnum3 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tnum3 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretBool1 {
        pub secret_x: Option<bool>,
    }

    impl pulumi::FromPropertyValue for TsecretBool1 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretBool1 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretBool2 {
        pub secret_x: Option<bool>,
    }

    impl pulumi::FromPropertyValue for TsecretBool2 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretBool2 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretBool3 {
        pub secret_x: Option<bool>,
    }

    impl pulumi::FromPropertyValue for TsecretBool3 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretBool3 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretInt1 {
        pub secret_x: Option<i32>,
    }

    impl pulumi::FromPropertyValue for TsecretInt1 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretInt1 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretInt2 {
        pub secret_x: Option<i32>,
    }

    impl pulumi::FromPropertyValue for TsecretInt2 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretInt2 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretInt3 {
        pub secret_x: Option<i32>,
    }

    impl pulumi::FromPropertyValue for TsecretInt3 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretInt3 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretNum1 {
        pub secret_x: Option<f64>,
    }

    impl pulumi::FromPropertyValue for TsecretNum1 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretNum1 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretNum2 {
        pub secret_x: Option<f64>,
    }

    impl pulumi::FromPropertyValue for TsecretNum2 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretNum2 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretNum3 {
        pub secret_x: Option<f64>,
    }

    impl pulumi::FromPropertyValue for TsecretNum3 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretNum3 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretString1 {
        pub secret_x: Option<std::string::String>,
    }

    impl pulumi::FromPropertyValue for TsecretString1 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretString1 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretString2 {
        pub secret_x: Option<std::string::String>,
    }

    impl pulumi::FromPropertyValue for TsecretString2 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretString2 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct TsecretString3 {
        pub secret_x: Option<std::string::String>,
    }

    impl pulumi::FromPropertyValue for TsecretString3 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(TsecretString3 {
                secret_x: pulumi::convert::from_property_map(&m, "secretX")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tstring1 {
        pub x: Option<std::string::String>,
    }

    impl pulumi::FromPropertyValue for Tstring1 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tstring1 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tstring2 {
        pub x: Option<std::string::String>,
    }

    impl pulumi::FromPropertyValue for Tstring2 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tstring2 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct Tstring3 {
        pub x: Option<std::string::String>,
    }

    impl pulumi::FromPropertyValue for Tstring3 {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(Tstring3 {
                x: pulumi::convert::from_property_map(&m, "x")?,
            })
        }
    }

    #[derive(Clone, Debug)]
    pub struct ToSecretResult {
        pub bool1: bool,
        pub bool2: bool,
        pub bool3: bool,
        pub int1: i32,
        pub int2: i32,
        pub int3: i32,
        pub list_bool1: std::vec::Vec<bool>,
        pub list_bool2: std::vec::Vec<bool>,
        pub list_bool3: std::vec::Vec<bool>,
        pub list_int1: std::vec::Vec<i32>,
        pub list_int2: std::vec::Vec<i32>,
        pub list_int3: std::vec::Vec<i32>,
        pub list_num1: std::vec::Vec<f64>,
        pub list_num2: std::vec::Vec<f64>,
        pub list_num3: std::vec::Vec<f64>,
        pub list_secret_bool1: std::vec::Vec<bool>,
        pub list_secret_bool2: std::vec::Vec<bool>,
        pub list_secret_bool3: std::vec::Vec<bool>,
        pub list_secret_int1: std::vec::Vec<i32>,
        pub list_secret_int2: std::vec::Vec<i32>,
        pub list_secret_int3: std::vec::Vec<i32>,
        pub list_secret_num1: std::vec::Vec<f64>,
        pub list_secret_num2: std::vec::Vec<f64>,
        pub list_secret_num3: std::vec::Vec<f64>,
        pub list_secret_string1: std::vec::Vec<std::string::String>,
        pub list_secret_string2: std::vec::Vec<std::string::String>,
        pub list_secret_string3: std::vec::Vec<std::string::String>,
        pub list_string1: std::vec::Vec<std::string::String>,
        pub list_string2: std::vec::Vec<std::string::String>,
        pub list_string3: std::vec::Vec<std::string::String>,
        pub map_bool1: std::collections::BTreeMap<std::string::String, bool>,
        pub map_bool2: std::collections::BTreeMap<std::string::String, bool>,
        pub map_bool3: std::collections::BTreeMap<std::string::String, bool>,
        pub map_int1: std::collections::BTreeMap<std::string::String, i32>,
        pub map_int2: std::collections::BTreeMap<std::string::String, i32>,
        pub map_int3: std::collections::BTreeMap<std::string::String, i32>,
        pub map_num1: std::collections::BTreeMap<std::string::String, f64>,
        pub map_num2: std::collections::BTreeMap<std::string::String, f64>,
        pub map_num3: std::collections::BTreeMap<std::string::String, f64>,
        pub map_secret_bool1: std::collections::BTreeMap<std::string::String, bool>,
        pub map_secret_bool2: std::collections::BTreeMap<std::string::String, bool>,
        pub map_secret_bool3: std::collections::BTreeMap<std::string::String, bool>,
        pub map_secret_int1: std::collections::BTreeMap<std::string::String, i32>,
        pub map_secret_int2: std::collections::BTreeMap<std::string::String, i32>,
        pub map_secret_int3: std::collections::BTreeMap<std::string::String, i32>,
        pub map_secret_num1: std::collections::BTreeMap<std::string::String, f64>,
        pub map_secret_num2: std::collections::BTreeMap<std::string::String, f64>,
        pub map_secret_num3: std::collections::BTreeMap<std::string::String, f64>,
        pub map_secret_string1: std::collections::BTreeMap<std::string::String, std::string::String>,
        pub map_secret_string2: std::collections::BTreeMap<std::string::String, std::string::String>,
        pub map_secret_string3: std::collections::BTreeMap<std::string::String, std::string::String>,
        pub map_string1: std::collections::BTreeMap<std::string::String, std::string::String>,
        pub map_string2: std::collections::BTreeMap<std::string::String, std::string::String>,
        pub map_string3: std::collections::BTreeMap<std::string::String, std::string::String>,
        pub num1: f64,
        pub num2: f64,
        pub num3: f64,
        pub obj_bool1: crate::types::Tbool1,
        pub obj_bool2: crate::types::Tbool2,
        pub obj_bool3: crate::types::Tbool3,
        pub obj_int1: crate::types::Tint1,
        pub obj_int2: crate::types::Tint2,
        pub obj_int3: crate::types::Tint3,
        pub obj_num1: crate::types::Tnum1,
        pub obj_num2: crate::types::Tnum2,
        pub obj_num3: crate::types::Tnum3,
        pub obj_secret_bool1: crate::types::TsecretBool1,
        pub obj_secret_bool2: crate::types::TsecretBool2,
        pub obj_secret_bool3: crate::types::TsecretBool3,
        pub obj_secret_int1: crate::types::TsecretInt1,
        pub obj_secret_int2: crate::types::TsecretInt2,
        pub obj_secret_int3: crate::types::TsecretInt3,
        pub obj_secret_num1: crate::types::TsecretNum1,
        pub obj_secret_num2: crate::types::TsecretNum2,
        pub obj_secret_num3: crate::types::TsecretNum3,
        pub obj_secret_string1: crate::types::TsecretString1,
        pub obj_secret_string2: crate::types::TsecretString2,
        pub obj_secret_string3: crate::types::TsecretString3,
        pub obj_string1: crate::types::Tstring1,
        pub obj_string2: crate::types::Tstring2,
        pub obj_string3: crate::types::Tstring3,
        pub secret_bool1: bool,
        pub secret_bool2: bool,
        pub secret_bool3: bool,
        pub secret_int1: i32,
        pub secret_int2: i32,
        pub secret_int3: i32,
        pub secret_num1: f64,
        pub secret_num2: f64,
        pub secret_num3: f64,
        pub secret_string1: std::string::String,
        pub secret_string2: std::string::String,
        pub secret_string3: std::string::String,
        pub string1: std::string::String,
        pub string2: std::string::String,
        pub string3: std::string::String,
    }

    impl pulumi::FromPropertyValue for ToSecretResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(ToSecretResult {
                bool1: pulumi::convert::from_property_map(&m, "bool1")?,
                bool2: pulumi::convert::from_property_map(&m, "bool2")?,
                bool3: pulumi::convert::from_property_map(&m, "bool3")?,
                int1: pulumi::convert::from_property_map(&m, "int1")?,
                int2: pulumi::convert::from_property_map(&m, "int2")?,
                int3: pulumi::convert::from_property_map(&m, "int3")?,
                list_bool1: pulumi::convert::from_property_map(&m, "listBool1")?,
                list_bool2: pulumi::convert::from_property_map(&m, "listBool2")?,
                list_bool3: pulumi::convert::from_property_map(&m, "listBool3")?,
                list_int1: pulumi::convert::from_property_map(&m, "listInt1")?,
                list_int2: pulumi::convert::from_property_map(&m, "listInt2")?,
                list_int3: pulumi::convert::from_property_map(&m, "listInt3")?,
                list_num1: pulumi::convert::from_property_map(&m, "listNum1")?,
                list_num2: pulumi::convert::from_property_map(&m, "listNum2")?,
                list_num3: pulumi::convert::from_property_map(&m, "listNum3")?,
                list_secret_bool1: pulumi::convert::from_property_map(&m, "listSecretBool1")?,
                list_secret_bool2: pulumi::convert::from_property_map(&m, "listSecretBool2")?,
                list_secret_bool3: pulumi::convert::from_property_map(&m, "listSecretBool3")?,
                list_secret_int1: pulumi::convert::from_property_map(&m, "listSecretInt1")?,
                list_secret_int2: pulumi::convert::from_property_map(&m, "listSecretInt2")?,
                list_secret_int3: pulumi::convert::from_property_map(&m, "listSecretInt3")?,
                list_secret_num1: pulumi::convert::from_property_map(&m, "listSecretNum1")?,
                list_secret_num2: pulumi::convert::from_property_map(&m, "listSecretNum2")?,
                list_secret_num3: pulumi::convert::from_property_map(&m, "listSecretNum3")?,
                list_secret_string1: pulumi::convert::from_property_map(&m, "listSecretString1")?,
                list_secret_string2: pulumi::convert::from_property_map(&m, "listSecretString2")?,
                list_secret_string3: pulumi::convert::from_property_map(&m, "listSecretString3")?,
                list_string1: pulumi::convert::from_property_map(&m, "listString1")?,
                list_string2: pulumi::convert::from_property_map(&m, "listString2")?,
                list_string3: pulumi::convert::from_property_map(&m, "listString3")?,
                map_bool1: pulumi::convert::from_property_map(&m, "mapBool1")?,
                map_bool2: pulumi::convert::from_property_map(&m, "mapBool2")?,
                map_bool3: pulumi::convert::from_property_map(&m, "mapBool3")?,
                map_int1: pulumi::convert::from_property_map(&m, "mapInt1")?,
                map_int2: pulumi::convert::from_property_map(&m, "mapInt2")?,
                map_int3: pulumi::convert::from_property_map(&m, "mapInt3")?,
                map_num1: pulumi::convert::from_property_map(&m, "mapNum1")?,
                map_num2: pulumi::convert::from_property_map(&m, "mapNum2")?,
                map_num3: pulumi::convert::from_property_map(&m, "mapNum3")?,
                map_secret_bool1: pulumi::convert::from_property_map(&m, "mapSecretBool1")?,
                map_secret_bool2: pulumi::convert::from_property_map(&m, "mapSecretBool2")?,
                map_secret_bool3: pulumi::convert::from_property_map(&m, "mapSecretBool3")?,
                map_secret_int1: pulumi::convert::from_property_map(&m, "mapSecretInt1")?,
                map_secret_int2: pulumi::convert::from_property_map(&m, "mapSecretInt2")?,
                map_secret_int3: pulumi::convert::from_property_map(&m, "mapSecretInt3")?,
                map_secret_num1: pulumi::convert::from_property_map(&m, "mapSecretNum1")?,
                map_secret_num2: pulumi::convert::from_property_map(&m, "mapSecretNum2")?,
                map_secret_num3: pulumi::convert::from_property_map(&m, "mapSecretNum3")?,
                map_secret_string1: pulumi::convert::from_property_map(&m, "mapSecretString1")?,
                map_secret_string2: pulumi::convert::from_property_map(&m, "mapSecretString2")?,
                map_secret_string3: pulumi::convert::from_property_map(&m, "mapSecretString3")?,
                map_string1: pulumi::convert::from_property_map(&m, "mapString1")?,
                map_string2: pulumi::convert::from_property_map(&m, "mapString2")?,
                map_string3: pulumi::convert::from_property_map(&m, "mapString3")?,
                num1: pulumi::convert::from_property_map(&m, "num1")?,
                num2: pulumi::convert::from_property_map(&m, "num2")?,
                num3: pulumi::convert::from_property_map(&m, "num3")?,
                obj_bool1: pulumi::convert::from_property_map(&m, "objBool1")?,
                obj_bool2: pulumi::convert::from_property_map(&m, "objBool2")?,
                obj_bool3: pulumi::convert::from_property_map(&m, "objBool3")?,
                obj_int1: pulumi::convert::from_property_map(&m, "objInt1")?,
                obj_int2: pulumi::convert::from_property_map(&m, "objInt2")?,
                obj_int3: pulumi::convert::from_property_map(&m, "objInt3")?,
                obj_num1: pulumi::convert::from_property_map(&m, "objNum1")?,
                obj_num2: pulumi::convert::from_property_map(&m, "objNum2")?,
                obj_num3: pulumi::convert::from_property_map(&m, "objNum3")?,
                obj_secret_bool1: pulumi::convert::from_property_map(&m, "objSecretBool1")?,
                obj_secret_bool2: pulumi::convert::from_property_map(&m, "objSecretBool2")?,
                obj_secret_bool3: pulumi::convert::from_property_map(&m, "objSecretBool3")?,
                obj_secret_int1: pulumi::convert::from_property_map(&m, "objSecretInt1")?,
                obj_secret_int2: pulumi::convert::from_property_map(&m, "objSecretInt2")?,
                obj_secret_int3: pulumi::convert::from_property_map(&m, "objSecretInt3")?,
                obj_secret_num1: pulumi::convert::from_property_map(&m, "objSecretNum1")?,
                obj_secret_num2: pulumi::convert::from_property_map(&m, "objSecretNum2")?,
                obj_secret_num3: pulumi::convert::from_property_map(&m, "objSecretNum3")?,
                obj_secret_string1: pulumi::convert::from_property_map(&m, "objSecretString1")?,
                obj_secret_string2: pulumi::convert::from_property_map(&m, "objSecretString2")?,
                obj_secret_string3: pulumi::convert::from_property_map(&m, "objSecretString3")?,
                obj_string1: pulumi::convert::from_property_map(&m, "objString1")?,
                obj_string2: pulumi::convert::from_property_map(&m, "objString2")?,
                obj_string3: pulumi::convert::from_property_map(&m, "objString3")?,
                secret_bool1: pulumi::convert::from_property_map(&m, "secretBool1")?,
                secret_bool2: pulumi::convert::from_property_map(&m, "secretBool2")?,
                secret_bool3: pulumi::convert::from_property_map(&m, "secretBool3")?,
                secret_int1: pulumi::convert::from_property_map(&m, "secretInt1")?,
                secret_int2: pulumi::convert::from_property_map(&m, "secretInt2")?,
                secret_int3: pulumi::convert::from_property_map(&m, "secretInt3")?,
                secret_num1: pulumi::convert::from_property_map(&m, "secretNum1")?,
                secret_num2: pulumi::convert::from_property_map(&m, "secretNum2")?,
                secret_num3: pulumi::convert::from_property_map(&m, "secretNum3")?,
                secret_string1: pulumi::convert::from_property_map(&m, "secretString1")?,
                secret_string2: pulumi::convert::from_property_map(&m, "secretString2")?,
                secret_string3: pulumi::convert::from_property_map(&m, "secretString3")?,
                string1: pulumi::convert::from_property_map(&m, "string1")?,
                string2: pulumi::convert::from_property_map(&m, "string2")?,
                string3: pulumi::convert::from_property_map(&m, "string3")?,
            })
        }
    }
}
