// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let first = pulumi_snake_names::cool_module::SomeResource::new(&ctx, "first", pulumi_snake_names::cool_module::SomeResourceArgs { nested: pulumi_snake_names::types::CoolModuleNestedInputArgs { nested_value: pulumi::ops::to_string(pulumi::pv::string("nested")).cast() }, the_input: pulumi::ops::to_bool(pulumi::pv::bool(true)).cast() }, pulumi::ResourceOptions::default());
        let third = pulumi_snake_names::cool_module::AnotherResource::new(&ctx, "third", pulumi_snake_names::cool_module::AnotherResourceArgs { the_input: pulumi::ops::to_string(pulumi_snake_names::cool_module::some_data(&ctx, pulumi_snake_names::cool_module::SomeDataArgs { nested: vec![pulumi_snake_names::types::CoolModuleEntryArgs { value: pulumi::ops::to_string(pulumi::pv::string("fuzz")).cast() }], the_input: pulumi::ops::to_string(first.the_output().cast::<pulumi::PropertyValue>().index("someKey").index(0usize).index("nested_output")).cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("nested_output").index(0usize).index("key").index("value")).cast() }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
