// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug)]
pub struct ResourceArgs {
    pub boolean: pulumi::Output<bool>,
    pub boolean_map: pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>,
    pub float: pulumi::Output<f64>,
    pub integer: pulumi::Output<i32>,
    pub number_array: pulumi::Output<std::vec::Vec<f64>>,
    pub string: pulumi::Output<std::string::String>,
}

impl ResourceArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.boolean;
            inputs.push(("boolean".to_string(), v.cast()));
        }
        {
            let v = self.boolean_map;
            inputs.push(("booleanMap".to_string(), v.cast()));
        }
        {
            let v = self.float;
            inputs.push(("float".to_string(), v.cast()));
        }
        {
            let v = self.integer;
            inputs.push(("integer".to_string(), v.cast()));
        }
        {
            let v = self.number_array;
            inputs.push(("numberArray".to_string(), v.cast()));
        }
        {
            let v = self.string;
            inputs.push(("string".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Resource {
    resource: pulumi::Resource,
}

impl Resource {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ResourceArgs, options: pulumi::ResourceOptions) -> Resource {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "primitive:index:Resource".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "7.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Resource { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }

    pub fn boolean(&self) -> pulumi::Output<bool> {
        self.resource.output("boolean").cast()
    }

    pub fn boolean_map(&self) -> pulumi::Output<std::collections::BTreeMap<std::string::String, bool>> {
        self.resource.output("booleanMap").cast()
    }

    pub fn float(&self) -> pulumi::Output<f64> {
        self.resource.output("float").cast()
    }

    pub fn integer(&self) -> pulumi::Output<i32> {
        self.resource.output("integer").cast()
    }

    pub fn number_array(&self) -> pulumi::Output<std::vec::Vec<f64>> {
        self.resource.output("numberArray").cast()
    }

    pub fn string(&self) -> pulumi::Output<std::string::String> {
        self.resource.output("string").cast()
    }
}

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:primitive".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "7.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct InvokeArgs {
    pub boolean: pulumi::Output<bool>,
    pub boolean_map: pulumi::Output<std::collections::BTreeMap<std::string::String, bool>>,
    pub float: pulumi::Output<f64>,
    pub integer: pulumi::Output<i32>,
    pub number_array: pulumi::Output<std::vec::Vec<f64>>,
    pub string: pulumi::Output<std::string::String>,
}

impl InvokeArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.boolean;
            inputs.push(("boolean".to_string(), v.cast()));
        }
        {
            let v = self.boolean_map;
            inputs.push(("booleanMap".to_string(), v.cast()));
        }
        {
            let v = self.float;
            inputs.push(("float".to_string(), v.cast()));
        }
        {
            let v = self.integer;
            inputs.push(("integer".to_string(), v.cast()));
        }
        {
            let v = self.number_array;
            inputs.push(("numberArray".to_string(), v.cast()));
        }
        {
            let v = self.string;
            inputs.push(("string".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn invoke(ctx: &pulumi::Context, args: InvokeArgs, options: pulumi::InvokeOptions) -> pulumi::Output<crate::types::InvokeResult> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "7.0.0".to_string();
    }
    ctx.invoke("primitive:index:invoke", args.into_inputs(), options).cast()
}

pub mod types {
    #[derive(Clone, Debug)]
    pub struct InvokeResult {
        pub boolean: bool,
        pub boolean_map: std::collections::BTreeMap<std::string::String, bool>,
        pub float: f64,
        pub integer: i32,
        pub number_array: std::vec::Vec<f64>,
        pub string: std::string::String,
    }

    impl pulumi::FromPropertyValue for InvokeResult {
        fn from_property_value(v: pulumi::PropertyValue) -> pulumi::Result<Self> {
            let m = <pulumi::PropertyMap as pulumi::FromPropertyValue>::from_property_value(v)?;
            Ok(InvokeResult {
                boolean: pulumi::convert::from_property_map(&m, "boolean")?,
                boolean_map: pulumi::convert::from_property_map(&m, "booleanMap")?,
                float: pulumi::convert::from_property_map(&m, "float")?,
                integer: pulumi::convert::from_property_map(&m, "integer")?,
                number_array: pulumi::convert::from_property_map(&m, "numberArray")?,
                string: pulumi::convert::from_property_map(&m, "string")?,
            })
        }
    }
}
