// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let example1 = pulumi_discriminated_union::Example::new(&ctx, "example1", pulumi_discriminated_union::ExampleArgs { array_of_union_of: Some(pulumi::pv::array(vec![pulumi::pv::object(vec![("discriminantKind".to_string(), pulumi::pv::string("variant1")), ("field1".to_string(), pulumi::ops::to_string(pulumi::pv::string("v1 array(union)")))])]).cast()), union_of: Some(pulumi::pv::object(vec![("discriminantKind".to_string(), pulumi::pv::string("variant1")), ("field1".to_string(), pulumi::ops::to_string(pulumi::pv::string("v1 union")))]).cast()) }, pulumi::ResourceOptions::default());
        let example2 = pulumi_discriminated_union::Example::new(&ctx, "example2", pulumi_discriminated_union::ExampleArgs { array_of_union_of: Some(pulumi::pv::array(vec![pulumi::pv::object(vec![("discriminantKind".to_string(), pulumi::pv::string("variant2")), ("field2".to_string(), pulumi::ops::to_string(pulumi::pv::string("v2 array(union)")))]), pulumi::pv::object(vec![("discriminantKind".to_string(), pulumi::pv::string("variant1")), ("field1".to_string(), pulumi::ops::to_string(pulumi::pv::string("v1 array(union)")))])]).cast()), union_of: Some(pulumi::pv::object(vec![("discriminantKind".to_string(), pulumi::pv::string("variant2")), ("field2".to_string(), pulumi::ops::to_string(pulumi::pv::string("v2 union")))]).cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
