// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let my_res = pulumi_enum::Res::new(&ctx, "myRes", pulumi_enum::ResArgs { int_enum: Some(pulumi::pv::number(1.0).cast()), string_enum: Some(pulumi::pv::string("one").cast()) }, pulumi::ResourceOptions::default());
        let my_sink = pulumi_extenumref::Sink::new(&ctx, "mySink", pulumi_extenumref::SinkArgs { string_enum: Some(pulumi::pv::string("two").cast()) }, pulumi::ResourceOptions::default());
        Ok(())
    });
}
