// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let local_value = pulumi::pv::string("hello");
        ctx.export("dynamic", pulumi_any_type_function::dyn_list_to_dyn(&ctx, pulumi_any_type_function::DynListToDynArgs { inputs: Some(pulumi::pv::array(vec![pulumi::pv::string("hello"), local_value.clone(), pulumi::pv::object(vec![])]).cast()) }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("result"));
        Ok(())
    });
}
