// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        ctx.export("hello", pulumi_output_only_invoke::my_invoke(&ctx, pulumi_output_only_invoke::MyInvokeArgs { value: pulumi::pv::string("hello").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("result"));
        ctx.export("goodbye", pulumi_output_only_invoke::my_invoke(&ctx, pulumi_output_only_invoke::MyInvokeArgs { value: pulumi::pv::string("goodbye").cast() }, pulumi::InvokeOptions::default()).cast::<pulumi::PropertyValue>().index("result"));
        Ok(())
    });
}
