// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

#[derive(Clone, Debug, Default)]
pub struct ProviderArgs {
}

impl ProviderArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

#[derive(Clone)]
pub struct Provider {
    resource: pulumi::Resource,
}

impl Provider {
    pub fn new(ctx: &pulumi::Context, name: &str, args: ProviderArgs, options: pulumi::ResourceOptions) -> Provider {
        let resource = ctx.register_resource(pulumi::RegisterRequest {
            type_: "pulumi:providers:scalar-returns".to_string(),
            name: name.to_string(),
            custom: true,
            remote: false,
            version: "21.0.0".to_string(),
            plugin_download_url: "".to_string(),
            inputs: args.into_inputs(),
            options,
        });
        Provider { resource }
    }

    pub fn pulumi_resource(&self) -> &pulumi::Resource {
        &self.resource
    }

    pub fn urn(&self) -> pulumi::Output<std::string::String> {
        self.resource.urn()
    }

    pub fn id(&self) -> pulumi::Output<std::string::String> {
        self.resource.id()
    }
}

#[derive(Clone, Debug)]
pub struct InvokeArrayArgs {
    pub value: pulumi::Output<std::string::String>,
}

impl InvokeArrayArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn invoke_array(ctx: &pulumi::Context, args: InvokeArrayArgs, options: pulumi::InvokeOptions) -> pulumi::Output<pulumi::PropertyValue> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "21.0.0".to_string();
    }
    pulumi::pv::single_value(ctx.invoke("scalar-returns:index:invokeArray", args.into_inputs(), options)).cast()
}

#[derive(Clone, Debug)]
pub struct InvokeMapArgs {
    pub value: pulumi::Output<std::string::String>,
}

impl InvokeMapArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn invoke_map(ctx: &pulumi::Context, args: InvokeMapArgs, options: pulumi::InvokeOptions) -> pulumi::Output<pulumi::PropertyValue> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "21.0.0".to_string();
    }
    pulumi::pv::single_value(ctx.invoke("scalar-returns:index:invokeMap", args.into_inputs(), options)).cast()
}

#[derive(Clone, Debug)]
pub struct InvokeSecretArgs {
    pub value: pulumi::Output<std::string::String>,
}

impl InvokeSecretArgs {
    pub fn into_inputs(self) -> std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> {
        let mut inputs: std::vec::Vec<(std::string::String, pulumi::Output<pulumi::PropertyValue>)> = std::vec::Vec::new();
        {
            let v = self.value;
            inputs.push(("value".to_string(), v.cast()));
        }
        inputs
    }

    pub fn into_output(self) -> pulumi::Output<pulumi::PropertyValue> {
        pulumi::output::object(self.into_inputs())
    }
}

pub fn invoke_secret(ctx: &pulumi::Context, args: InvokeSecretArgs, options: pulumi::InvokeOptions) -> pulumi::Output<pulumi::PropertyValue> {
    let mut options = options;
    if options.version.is_empty() {
        options.version = "21.0.0".to_string();
    }
    pulumi::pv::single_value(ctx.invoke("scalar-returns:index:invokeSecret", args.into_inputs(), options)).cast()
}

