// Code generated by pulumi-language-rust. DO NOT EDIT.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, clippy::all)]

fn main() {
    pulumi::run(|ctx| async move {
        let set_res = pulumi_optional_primitive_ref::Resource::new(&ctx, "setRes", pulumi_optional_primitive_ref::ResourceArgs { data: pulumi_optional_primitive_ref::types::DataArgs { boolean: Some(pulumi::ops::to_bool(pulumi::pv::bool(true)).cast()), boolean_map: Some(pulumi::pv::object(vec![("t".to_string(), pulumi::ops::to_bool(pulumi::pv::bool(true))), ("f".to_string(), pulumi::ops::to_bool(pulumi::pv::bool(false)))]).cast()), float: Some(pulumi::ops::to_number(pulumi::pv::number(3.14)).cast()), integer: Some(pulumi::ops::to_int(pulumi::pv::number(42.0)).cast()), number_array: Some(pulumi::pv::array(vec![pulumi::ops::to_number(pulumi::pv::number(-1.0)), pulumi::ops::to_number(pulumi::pv::number(0.0)), pulumi::ops::to_number(pulumi::pv::number(1.0))]).cast()), string: Some(pulumi::ops::to_string(pulumi::pv::string("hello")).cast()) }, optional_data: Some(pulumi_optional_primitive_ref::types::DataArgs { boolean: None, boolean_map: None, float: None, integer: None, number_array: None, string: Some(pulumi::ops::to_string(pulumi::pv::string("optional parent")).cast()) }) }, pulumi::ResourceOptions::default());
        let unset_res = pulumi_optional_primitive_ref::Resource::new(&ctx, "unsetRes", pulumi_optional_primitive_ref::ResourceArgs { data: pulumi_optional_primitive_ref::types::DataArgs { boolean: None, boolean_map: None, float: None, integer: None, number_array: None, string: None }, optional_data: None }, pulumi::ResourceOptions::default());
        let from_nested_optional = pulumi_optional_primitive_ref::Resource::new(&ctx, "fromNestedOptional", pulumi_optional_primitive_ref::ResourceArgs { data: pulumi_optional_primitive_ref::types::DataArgs { boolean: None, boolean_map: None, float: None, integer: None, number_array: None, string: Some(pulumi::ops::to_string(set_res.optional_data().cast::<pulumi::PropertyValue>().index("string")).cast()) }, optional_data: None }, pulumi::ResourceOptions::default());
        ctx.export("setBoolean", set_res.data().cast::<pulumi::PropertyValue>().index("boolean"));
        ctx.export("setFloat", set_res.data().cast::<pulumi::PropertyValue>().index("float"));
        ctx.export("setInteger", set_res.data().cast::<pulumi::PropertyValue>().index("integer"));
        ctx.export("setString", set_res.data().cast::<pulumi::PropertyValue>().index("string"));
        ctx.export("setNumberArray", set_res.data().cast::<pulumi::PropertyValue>().index("numberArray"));
        ctx.export("setBooleanMap", set_res.data().cast::<pulumi::PropertyValue>().index("booleanMap"));
        ctx.export("unsetBoolean", pulumi::ops::cond(pulumi::ops::eq(unset_res.data().cast::<pulumi::PropertyValue>().index("boolean"), pulumi::pv::null()), pulumi::pv::string("null"), pulumi::pv::string("not null")));
        ctx.export("unsetFloat", pulumi::ops::cond(pulumi::ops::eq(unset_res.data().cast::<pulumi::PropertyValue>().index("float"), pulumi::pv::null()), pulumi::pv::string("null"), pulumi::pv::string("not null")));
        ctx.export("unsetInteger", pulumi::ops::cond(pulumi::ops::eq(unset_res.data().cast::<pulumi::PropertyValue>().index("integer"), pulumi::pv::null()), pulumi::pv::string("null"), pulumi::pv::string("not null")));
        ctx.export("unsetString", pulumi::ops::cond(pulumi::ops::eq(unset_res.data().cast::<pulumi::PropertyValue>().index("string"), pulumi::pv::null()), pulumi::pv::string("null"), pulumi::pv::string("not null")));
        ctx.export("unsetNumberArray", pulumi::ops::cond(pulumi::ops::eq(unset_res.data().cast::<pulumi::PropertyValue>().index("numberArray"), pulumi::pv::null()), pulumi::pv::string("null"), pulumi::pv::string("not null")));
        ctx.export("unsetBooleanMap", pulumi::ops::cond(pulumi::ops::eq(unset_res.data().cast::<pulumi::PropertyValue>().index("booleanMap"), pulumi::pv::null()), pulumi::pv::string("null"), pulumi::pv::string("not null")));
        Ok(())
    });
}
